### ISSUE TITLE
Add example of what a layout file would look like

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#110]
Add an example of what a layout file would look like when used with `Bamboo.Phoenix`. I always forget how to call `render` with the assigns and I'm sure others will have to look it up as well. Might be worth including an example to save some time and make it easier to use the library.

**Comment by jerodsanto** [comment]
This would be super useful. Specifically, it'd be nice to see how we can use route helpers in layouts/templates since `@conn` isn't a thing.

_(I have a decent/simple sign in email w/ layout example I can provide once it's 💯 . Just let me know if/where you want it.)_

**Comment by paulcsmith** [comment]
@jerodsanto It would be wonderful if you could paste an example here or open up a PR. Especially if it includes using `MyApp.Endpoint` in URL helpers so that people can see how to use those. Thanks for offering to help!

**Comment by jerodsanto** [comment]
@paulcsmith happy to PR. Where do you want it the example to go? `bamboo/lib/bamboo/phoenix.ex`?

There are a few files...

**Comment by paulcsmith** [comment]
Yes, Bamboo.Phoenix would be perfect!

**Comment by paulcsmith** [comment]
Closed by #173
