### ISSUE TITLE
Raise if there is no html or text unless you explicitly set them both to empty

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#13]
This makes it easier to find out when you accidentally forget to render the body, but still allows you to leave it empty if you really want to.

The reason that you might want to set empty html and text bodies is that some adapters may be used to render emails from another service. For example, you can use Mandrill to render responsive templates that are rendered on their server, so you would not set a text or html body

**Comment by anellis** [comment]
@paulcsmith I can take care of this if you'd like. 

To make sure I understand correctly, you want it to be that if you just did something like 
`new_email() |> Bamboo.TestAdapter.deliver` it would raise an error stating that you haven't rendered a text or email body, correct?

**Comment by paulcsmith** [comment]
@anellis Yeah exactly, but I'm not totally sure that this should be done yet. I think it requires a bit more thought since I'd like to make it so that you can render an empty body if you want to, but maybe that doesn't matter. I'll ping you when I have something a bit more concrete!

**Comment by germsvel** [comment]
I'm gonna go ahead and close this issue. I don't know that we've had any further developments on this since it was first opened. But if others feel like this should be reopened, please let me know! Happy to have this open if we can make progress on it.
