### ISSUE TITLE
Add option to configure Task.SupervisorStrategy

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#134]
`config :bamboo, :task_supervisor_delivery_strategy, max_restarts: 10, restart_strategy: :transient`

This can be done post 1.0 since it would not be backwards incompatible

**Comment by germsvel** [comment]
I'm going to close this since it's a fairly old issue, and I'm not sure if people want to configure this. If someone wants this, I'd be happy to reopen it.
