### ISSUE TITLE
Content invisible except on gmail

### ISSUE THREAD

**Issue by pyladune** [thoughtbot/bamboo#171]
Is there a trick (or a bug ?) in the fact that content of HTML emails are just not displayable in emails clients except gmail ?

**Comment by pyladune** [comment]
ok. this concerns only SMTP message so probably more a concern for bamboo_smtp adapter

**Comment by paulcsmith** [comment]
Yes I think opening an issue on Bamboo SMTP would be the best bet here. Thank you!
