### ISSUE TITLE
Bamboo.EmailPreviewPlug could warn if the wrong adapter is configured

### ISSUE THREAD

**Issue by bratsche** [thoughtbot/bamboo#175]
I'm stupid and copied-pasted the config from my `test.exs` into my `dev.exs` and was surprised initially when emails did not appear in my previewer.

It would be nice if the email preview plug would notice if you have the wrong adapter configured and tell you.

**Comment by paulcsmith** [comment]
I was thinking about this and maybe the best thing to do is keep it simple and include a short list of reasons there might not be email when previewing. So something like

> Reasons emails may not be showing up
* **Not using Bamboo.LocalAdapter**. Make sure you have your mailer set up to use Bamboo.LocalAdapter or the emails will not show up here.
* **You may have restarted your server**. When the server restarts the emails are cleared.

**Comment by bratsche** [comment]
That makes sense. I'll send you a pull request tonight.
