### ISSUE TITLE
Style the "No email sent page"

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#181]
See issue #177 

Here is what it looks like now:

<img width="800" alt="screen shot 2016-06-20 at 3 57 22 pm" src="https://cloud.githubusercontent.com/assets/22394/16208352/b13f0c76-36ff-11e6-94cf-896af8f331db.png">

I think it doesn't quite flow right. The "reasons" text should likely be aligned to the left as well

**Comment by paulcsmith** [comment]
I did this in the browser so just need to actually do this in the code. Something like

<img width="726" alt="screen shot 2016-06-20 at 4 00 38 pm" src="https://cloud.githubusercontent.com/assets/22394/16208447/30cf2afc-3700-11e6-84fb-8a8acd3e9155.png">

**Comment by StevenXL** [comment]
Hello - I am trying to address this in PR #183. That PR is currently failing but I will address it on the PR rather than on the issue.

**Comment by paulcsmith** [comment]
Closed by #188
