### ISSUE TITLE
Warnings when compiling under Elixir 1.3

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/bamboo#187]
```
warning: function Phoenix.View.render_to_string/3 is undefined (module Phoenix.View is not available)
Found at 2 locations:
  lib/bamboo/phoenix.ex:271
  lib/bamboo/phoenix.ex:281
```

**Comment by geofflane** [comment]
I didn't see this warning when I checked out and did a clean compile with Elixir 1.3. Is it possible that you had old dependencies built with a previous Elixir version?

**Comment by paulcsmith** [comment]
I think it only shows up when being included in a project and recompiling. In dev and test I don’t thin it shows up because phoenix is a dependency of Bamboo for those environments.

**Comment by freiden** [comment]
@paulcsmith I'm using the version 0.8 of the library and I'm still seeing the warning fixed in #214 is it normal?

**Comment by paulcsmith** [comment]
@freiden This should be fixed in the next release. I fix was just merged a couple hours ago https://github.com/thoughtbot/bamboo/pull/304 👍

**Comment by paulcsmith** [comment]
Alternatively you could use master to get the latest stuff

**Comment by freiden** [comment]
@paulcsmith Thanks I will
