### ISSUE TITLE
Configuring app at runtime with exrm+conform

### ISSUE THREAD

**Issue by nauger** [thoughtbot/bamboo#200]
We're now using exrm and conform to build releases, but provide configuration at runtime.

It _looks_ like the configuration that is set (in prod.exs) is baked into the compiled result, such that we can't change this setting when our Phoenix Endpoint boots.

**Comment by paulcsmith** [comment]
@nauger This should be fixed in master and will go out in the next release. Can you give master a try and see if that works for you?

**Comment by paulcsmith** [comment]
I'm going to close this for now, but please reopen if it's still an issue for you! :)
