### ISSUE TITLE
No documentation how to preview email in real email managers

### ISSUE THREAD

**Issue by asiniy** [thoughtbot/bamboo#206]
I haven't found any documentation how can I export sending HTML to somewhere and then open it not in browser but in real email messengers like Thunderbird. I presume this way exists, but how can I do that?

**Comment by paulcsmith** [comment]
There is no way to preview in a real email client (that I know of). The way to do this would be to use a real adapter (like SMTP or Sendgrid) and actually send yourself an email. I hope that helps!
