### ISSUE TITLE
deliver vs deliver! (and the raising of errors from the adapters)

### ISSUE THREAD

**Issue by craigp** [thoughtbot/bamboo#220]
Just wanted to discuss this before opening a PR - I've been using bamboo and it's Sendgrid adapter, but one thing I noticed was that when you call `deliver_now/0` (and by extension `deliver/2` on the adapter) and something fails on the post to Sendgrid's API it raises an `ApiError`. This isn't really the behaviour I'd expect - in my case I'd like to react to errors by reporting on them and then possibly scheduling a retry, so it's preferable for me to receive the `{:error, reason}` tuple.

Indeed, this would in my experience so far to be the standard way to return from a function like this, whereas perhaps a `deliver!/2` function (possible called from `deliver_now!/0`) might be expected to raise an error.

Was the raising of errors a deliberate design decision or would you be open to a PR that addresses this?

**Comment by jbernardo95** [comment]
@craigp Related discussion: #196

**Comment by paulcsmith** [comment]
Closing this. I left a comment here: https://github.com/thoughtbot/bamboo/issues/196#issuecomment-255759381 addressing why there is no tagged tuple version of this function. Thanks for posting though. I appreciate the thoughts!
