### ISSUE TITLE
Add option to open new email with LocalAdapter automatically

### ISSUE THREAD

**Issue by sbrink** [thoughtbot/bamboo#221]
If you're testing workflows locally, it would be nice to open new mails in a new tab.

**Why?**

Even if you have tests, you sometimes want to go through your application manually. In our application we have support for passwordless login. It's really annoying to leave a tab open for http://localhost:4000/sent_emails. 

**Solution**

An easy solution would be to add a config option to the LocalAdapter.

_dev.exs_

```
config :my_app, MyApp.Mailer,
  adapter: Bamboo.LocalAdapter,
  popup_at: "http://localhost:4000/sent_emails"
```

Here is a working example for macOS

_bamboo/adapters/local_adapter.ex_

```
  def deliver(email, config) do
    email = SentEmail.push(email)
    email_id = email.private.local_adapter_id
    open_browser("#{config.popup_at}/#{email_id}")
  end

  defp open_browser(url) do
    System.cmd("open", [url])
  end
```

I'd work on supporting Windows and Linux as well.

Are you interested in a pull request? Would you prefer a config option or a new adapter?

**Comment by schurig** [comment]
+1 for a config option

**Comment by paulcsmith** [comment]
This is a very interesting idea. I'm definitely open to a PR and I think that a config option would be great. Something like "open_emails_in_browser".

Thanks for the awesome idea!

**Comment by KillerCodeMonkey** [comment]
+1 nice idea!

**Comment by sbrink** [comment]
I added a pull request for this option: #222.

This is manually testing in virtual boxes for Windows, Linux (Ubuntu) and macOS.

Any ideas how to test this properly?

**Comment by kelvinst** [comment]
I guess this can be closed since it's released right?
