### ISSUE TITLE
Add option for using proxy in mailgun adaptor

### ISSUE THREAD

**Issue by tslcjames** [thoughtbot/bamboo#223]
Hi,
I try to use mailgun adaptor with proxy, but there is not option for that
Add the option in mailgun adaptor here, https://github.com/tslcjames/bamboo/commit/d10fb1d51737d1b505de5462a2e25988f13744b4
could we have some option like that?

**Comment by JamesLaiv** [comment]
@paulcsmith should I create PR from my fork repo?
https://github.com/tslcjames/bamboo/commit/d10fb1d51737d1b505de5462a2e25988f13744b4

**Comment by tslcjames** [comment]
@paulcsmith should I create PR from my fork repo?
https://github.com/tslcjames/bamboo/commit/d10fb1d51737d1b505de5462a2e25988f13744b4

**Comment by lancejjohnson** [comment]
@tslcjames If this is still an issue, please feel free to open a pull request with your recommendation.

**Comment by tslcjames** [comment]
hi @lancejjohnson 
sorry, just want to confirm, how should I setup proxy at current implementation?

**Comment by germsvel** [comment]
Hi @tslcjames thanks for the patience with the issue. I'm beginning to maintain Bamboo. 

I believe this was resolved in https://github.com/thoughtbot/bamboo/pull/498, so I'm going to close this issue. 

You should be able to specify the hackney options you need (including the proxy) via `hackney_opts` in your config file (see the sample config in https://hexdocs.pm/bamboo/Bamboo.MailgunAdapter.html#module-example-config): 

```elixir
config :my_app, MyApp.Mailer,
  adapter: Bamboo.MailgunAdapter,
  api_key: "my_api_key" # or {:system, "MAILGUN_API_KEY"},
  domain: "your.domain" # or {:system, "MAILGUN_DOMAIN"},
  hackney_opts: [
    recv_timeout: :timer.minutes(1)
  ]
```
