### ISSUE TITLE
A possible bug in documentation?

### ISSUE THREAD

**Issue by explorer2309** [thoughtbot/bamboo#227]
I am Phoenix/Elixir newbie. I am trying to follow the documentation
here: http://www.phoenixframework.org/docs/sending-email
and here: https://lpil.uk/blog/sending-email-via-smtp-with-elixir-phoenix/

I appreciate these are not your project documentation. Apologies for seeking help for my confusion to this forum.

My code is same as that in the documentation above. But, when I try to send email from my controller, I get the following error:
`** (UndefinedFunctionError) function MyApp.Email.welcome_text_email/1 is undefined (module MyApp.Email is not available)`

This is my controller code:
```
  def create(conn, %{"contact" => contact_params}) do
    changeset = Contact.changeset(%Contact{}, contact_params)

    case Repo.insert(changeset) do
      {:ok, contact} ->
        
        MyApp.Email.welcome_text_email(contact.email)
        |> Mailer.deliver_later

        conn
        |> put_status(:created)
        |> put_resp_header("location", contact_path(conn, :show, contact))
        |> render("show.json", contact: contact)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(MyApp.ChangesetView, "error.json", changeset: changeset)
    end
  end
```

I can see that the Email module is not available to the application.

Do I need to register the Email module somewhere before being able to call it? or should everything in lib module be available to the controllers?

**Comment by explorer2309** [comment]
Ignore me. I was being an idiot :(

**Comment by newstler** [comment]
How did you solve it? I'm stuck with the same problem
