### ISSUE TITLE
Support for mail headers in Mailgun adapter

### ISSUE THREAD

**Issue by a12e** [thoughtbot/bamboo#232]
According to [Mailgun documentation](https://documentation.mailgun.com/api-sending.html#sending) one can set custom mail headers by adding a field prefixed with `h:` in the HTTP request:

> h:X-My-Header 	h: prefix followed by an arbitrary value allows to append a custom MIME header to the message (X-My-Header in this case). For example, h:Reply-To to specify Reply-To address.

With Bamboo we set headers with the `Email.put_header/3` function. They are stored in the `headers` map of the `Email` struct. But the Mailgun adapter doesn't make use of them at the moment.

Would it be possible to implement that? It doesn't seem complicated.

**Comment by jbernardo95** [comment]
@a12e Opened a PR regarding this, can you take a look and see if this is what you requested ?

**Comment by a12e** [comment]
Yes, exactly. Good job 👍
