### ISSUE TITLE
Getting emails from TestAdapter

### ISSUE THREAD

**Issue by optikfluffel** [thoughtbot/bamboo#233]
Is there a way to get the emails sent through [`Bamboo.TestAdapter`](https://hexdocs.pm/bamboo/Bamboo.TestAdapter.html)?

I'm trying to test a passwordless `SessionController` in which I generate a [`Phoenix.Token`](https://hexdocs.pm/phoenix/Phoenix.Token.html) and send it out via email without storing it anywhere. It would be cool to be able to catch these emails and read the tokens to test the sign in mechanism.

**Comment by paulcsmith** [comment]
@optikfluffel I think the best way to handle this might be to do a unit test on the email. That way you can do something like:

```elixir
assert email.html_body =~ the_generated_token
```

Then in your integration tests you can use the new feature in #228 to test that the email with the correct subject is sent. Either that or use a fake token during test so it's always the same. Then you can use regular `assert_delivered` and pass it an email. If you use a fake token that's always the same, then the body should be the same and the current test functions should do the trick. Does that help?

**Comment by optikfluffel** [comment]
The unit test I already had ^^
Using the `:subject` for integration testing, when #228 is ready, sounds fine.

Thanks :)

FYI: To test my sign in mechanism, since it only checks if the `:token` is younger than a minute and then uses the signed content to get the user out of the database, I simply generate a brand new one inside the test so I don't rely on mail things there (which feels somewhat cleaner as well).

**Comment by petejkim** [comment]
I ran into a similar issue recently, I ended up doing the following to get the `Bamboo.Email` struct:

```elixir
assert_receive({:delivered_email, %Bamboo.Email{} = email}, 100, Bamboo.Test.flunk_no_emails_received)
```
