### ISSUE TITLE
Phoenix rendering can break from a clean install

### ISSUE THREAD

**Issue by bgeihsgt** [thoughtbot/bamboo#236]
I made this comment on https://github.com/thoughtbot/bamboo/pull/214 but I should probably open a formal issue for this.

I recently upgraded to latest at master found the PR above may have caused a problem when installing all dependencies from scratch in my phoenix project. Here's a repro using my test suite:

```
mix deps.clean
mix deps.get
mix test
```

Any of my tests rendering emails then fail with the "phoenix is required" error. If I recompile the bamboo dependency again, things start working:

```
MIX_ENV=test mix deps.compile --force bamboo
```

Note: I'm also referencing bamboo as a git dependency as a fork of this repo. I'm not sure if that has something to do with the dependency ordering.

**Comment by snewcomer** [comment]
same here

**Comment by paulcsmith** [comment]
I think what I'm gong to do is extract the phoenix parts to a `bamboo_phoenix` library. That way the condition logic is removed and that should fix the issues. I've been on vacation but I'll tackle this next week!

**Comment by bgeihsgt** [comment]
Great to hear, thanks @paulcsmith!

**Comment by paulcsmith** [comment]
I decided to keep Bamboo Phoenix here for now and remove the Phoenix checks. I'll likely split it apart later, but this should work for now 👍 

Let me know if the latest on master fix the issues for you
