### ISSUE TITLE
Specify root domain for email links

### ISSUE THREAD

**Issue by shawnbro** [thoughtbot/bamboo#237]
Is there any way to programmatically specify the root domain which should be used when creating links in emails?

(Something similar to what's specified here in Rails ActionMailer http://guides.rubyonrails.org/action_mailer_basics.html#generating-urls-in-action-mailer-views)

**Comment by jbernardo95** [comment]
@shawnbro Bamboo uses `Phoenix.View.render_to_string` function to render Phoenix views.

So you have two options: you either specify the full URL on the template, or you create your own `link` helper which gets the root url from somewhere (if Phoenix `link` helper doens't do this already, I am not familiarised enough with Phoenix to know that, but a with a quick search should be something easy to find).

In any way, Bamboo's responsibility is to provide you with a simple interface to manage emails, so what you were asking is not possible to do on the Bamboo side.

@paulcsmith Am I right ?

**Comment by paulcsmith** [comment]
Yes I believe this is beyond the scope of Bamboo, and is part of Phoenix if that's what you want. You can use the regular link helpers and pass your endpoint to the url helper.

```
<%= link "Users!", to: users_url(MyApp.Endpoint, :index) %>
```

Just make sure you set the correct host for the endpoint in `config/prod.exs` :)

If you're not using Phoenix then I would make a function that generates URLs with the domain you want. I'm going to close this, but feel free to leave a comment if you need further clarification.

Thanks for the comment @jbernardo95!
