### ISSUE TITLE
MyApp.Email vs MyApp.Emails in README

### ISSUE THREAD

**Issue by wojtekmach** [thoughtbot/bamboo#238]
I noticed that README is using both `MyApp.Email` and `MyApp.Emails` - do you have a recommendation how to name the module? Obviously it's up to the user but I think it would be good to be consistent.

PS one merit of calling it `MyApp.Emails` is that it won't clash with `MyApp.Email` schema if one would ever need it (e.g. user could have multiple email addresses)

**Comment by jbernardo95** [comment]
@wojtekmach As you said it is up to the user to decide.

However I agree with you, I think `MyApp.Emails` is a better name, and the `README.md` is indeed inconsistent.

If you happen to have a large number of emails I suggest splitting them by several modules , for example `MyApp.CustomerEmails`, `MyApp.ProductEmails`, and so on, always appending `Emails` to the name of the module.

**Comment by jbernardo95** [comment]
@wojtekmach @paulcsmith Opened a PR to fix the inconsistency ^
