### ISSUE TITLE
Mailgun Adapter Configuration

### ISSUE THREAD

**Issue by odiumediae** [thoughtbot/bamboo#247]
I'm sorry, if I'm doing something wrong, but I've been fighting with this for two hours now, and I'm not able to make out what the actual problem is. Maybe it's a bug, maybe I'm an utter idiot.

I'm trying to use the Mailgun adapter, just like it's done in the example in the [documentation](https://hexdocs.pm/bamboo/Bamboo.MailgunAdapter.html). I'm absolutely positive that the credentials are correct, since I am using them in another app, but with [Chris McCord's Mailgun client](https://github.com/chrismccord/mailgun) and they work, of cource.

Whenever I try to use them with the Bamboo Mailgun adapter, however, I'm getting HTTP errors (301: moved permanently).

Is it a known bug? Am I an idiot? Can anybody confirm or refute that error?

**Comment by paulcsmith** [comment]
Hi @odiumediae, I don't personally use that adapter so I'm not sure. This is the first I've heard about an issue with the Mailgun adapter. I would try StackOverflow or the Elixir Slack room.

Also, maybe @princemaple knows something about it since he was the primary author of the Mailgun adapter

**Comment by princemaple** [comment]
What did you set as the domain?
301s appear mostly when there's an error in the URL.
And we build the URL from base uri and domain config. Base uri is hard coded, so I'd assume it's your domain.

**Comment by odiumediae** [comment]
Hi @paulcsmith, and thank you for replying.

Also thank you, @princemaple. I did set the exact domain given in the Mailgun backend, with the protocol (https). I tried it without the protocol, and leaving out the domain (https://api.mailgun.net). Whatever I try, it just won't work. I'm working from a local machine, by the way (but as I understand it should work anyway).

I appreciate any help, here.

**Comment by princemaple** [comment]
The domain is supposed to be the one that you have put into mailgun and you want to send emails from, e.g. "yourdomain.com", and yes without the protocol.

**Comment by odiumediae** [comment]
@princemaple: I don't know how I could miss that while looking at the source. My mistake was keeping the `v3/` part of the URI in my domain environment variable.

Thank you very much for your help, and I'm honestly sorry for having wasted your time with this rather simple problem. I must have had blinders on.

**Comment by princemaple** [comment]
No worries @odiumediae , everyone has this kind of moments every now and then.

**Comment by antalvarenga** [comment]
I had the same problem. I think it this should be pointed in the docs
