### ISSUE TITLE
Add support for using the 'reply_to' property with SendGrid

### ISSUE THREAD

**Issue by cjpwrs** [thoughtbot/bamboo#253]
Hello,

I've been using bamboo with the SendGrid adapter for a few months now. I am working on a new project that requires that I make use of the `reply_to` property that SendGrid's API supports. I'm going to try working on a solution, but figured I would mention it here first in case I've overlooked anything that already exists for this. Thanks.

**Comment by cjpwrs** [comment]
#254

**Comment by paulcsmith** [comment]
Closed by #254
