### ISSUE TITLE
ShellAdapter

### ISSUE THREAD

**Issue by Grafikart** [thoughtbot/bamboo#255]
This is a feature idea before doing a PR. Would you be interested by a shell adapter that would use 

```
System.cmd("mail", [...])
```

to send an email. 

I'm working on a project that doesn't use SMTP and I have to create this adapter so tell me if you want a PR with such an adapter and how it should be named.

Thanks for your work

**Comment by paulcsmith** [comment]
Hi @Grafikart. That's a very interesting idea. In the future I'm going to split out all the adapters into their own repos. If you would like to add a shell adapter I recommend doing something like https://github.com/pablo-co/bamboo_postmark, releasing it to hex and then open a PR here on Bamboo so people know about it. You can follow the example of this PR: https://github.com/thoughtbot/bamboo/pull/210

Thanks a ton! Let me know if you need any help
