### ISSUE TITLE
Example of DeliverLaterStrategy for Exq?

### ISSUE THREAD

**Issue by brandonparsons** [thoughtbot/bamboo#256]
Hi there,

Trying to send my emails in an `Exq` job queue (want the retry on failure behaviour).

Do you have any examples of how to accomplish this? I've tried doing a very naive port of your strategy examples, but am having trouble when it tries to JSON encode the `%Bamboo.Email{}` struct to store the job in Redis.

Have tried converting the struct to binary, but that's blowing up for other reasons....

```elixir
defmodule MyApp.Email.BackgroundJobDeliveryStrategy do
  # ------------------------------------------ #

  @behaviour Bamboo.DeliverLaterStrategy

  # ------------------------------------------ #

  def deliver_later(adapter, email, config) do
    data = email |> encode_email()
    {:ok, _jid} = Exq.enqueue(Exq, "emails", __MODULE__, [adapter, data, config])
  end

  def perform(adapter, binary, config) do
    binary |> decode_email() |> adapter.deliver(config)
  end

  # ------------------------------------------ #

  defp encode_email(%Bamboo.Email{} = email), do: :erlang.term_to_binary(email)
  defp decode_email(binary) when is_binary(binary), do: %Bamboo.Email{} = :erlang.binary_to_term(binary)
end
```

**Comment by paulcsmith** [comment]
I've never used `Exq`, but I imagine that you would want to store the data as JSON using `Poison`. So maybe something like:

```elixir
defp encode_email(%Bamboo.Email{} = email), do: Poison.encode!(email)
defp decode_email(email), do: %Bamboo.Email{} = Poison.decode!(email)
```

Like I said, I'm not sure what Exq expects to receive and what it returns, but something like this might work. I'm going to close this for now, but feel free to comment on it. You may also want to try the Elixir Slack group or the Elixir forum.

**Comment by brandonparsons** [comment]
@paulcsmith Thanks for the reply.

`Bamboo` emails can't be cleanly encoded/decoded by `Poison`, I think due to the use of tuples for `to`/`from`.  Is there a standard approach for this?

```
** (Poison.EncodeError) unable to encode value: {nil, "email@from.com"}
       (poison) lib/poison/encoder.ex:377: Poison.Encoder.Any.encode/2
       (poison) lib/poison/encoder.ex:223: anonymous fn/4 in Poison.Encoder.Map.encode/3
       (poison) lib/poison/encoder.ex:224: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
       (poison) lib/poison/encoder.ex:224: Poison.Encoder.Map.encode/3
       (poison) lib/poison.ex:41: Poison.encode!/2
    (my_app) lib/my_app/email/background_delivery_strategy.ex:9: MyApp.Email.BackgroundDeliveryStrategy.deliver_later/3
       (bamboo) lib/bamboo/mailer.ex:136: Bamboo.Mailer.deliver_later/3
```

**Comment by paulcsmith** [comment]
@brandonparsons I would convert the tuple into another structure that Poison can handle. Something like this

```elixir
def encode(email) do
  email 
  |> Map.from_struct 
  |> format_from_address
  |> format_recipients(:to)
  |> format_recipients(:cc)
  # ...etc
  |> Poison.encode!
end

defp format_from_address(email) do
  Map.update! email, :from, &format_address/1
end

defp format_recipients(email, field) do
  Map.update! email, field, fn(email_addresses) ->
    email_addresses |> Enum.map(&format_address/1)
  end
end

defp format_address(email_address) do
  %{name: elem(email_address, 0), address: elem(email_address, 1)}
end
```

And to decode you do the same thing in reverse where you convert the map to a tuple

```elixir
decoded_email = email
  |> Poison.decode!
  |> decode_from_address
  # ...etc.

struct(Bamboo.Email, decoded_email)

defp decode_from_address(email) do
  Map.update! email, :from, fn(email_address) ->
    {email_address.name, email_address.address}
  end
end
```

Does that make sense? I think that should work

**Comment by brandonparsons** [comment]
@paulcsmith Yeah that makes sense - thanks. I'll give it a shot. I was going down completely the wrong route (reasonably new to Elixir), and those {name, email} tuples were messing with me.

**Comment by brandonparsons** [comment]
Awesome @sickill. If the maintainers are open to it, I'd suggest just throwing what you have in your comment into the README under "Integration with Exq".

As a beginner to the Elixir ecosystem, this was a pretty early need for me, and it requires an understanding of quite a few concepts to get to that spot. Would be helpful!

**Comment by punitcse** [comment]
Thanks @sickill really helpful 👍
