### ISSUE TITLE
Mailgun Adapter not sending parameters, lock hackney to 1.6.5 

### ISSUE THREAD

**Issue by Grafikart** [thoughtbot/bamboo#258]
Mailgun Adapter will throw an error when sending an email telling `'from' parameter is missing`, but I send this params 

```
Here are the params we sent:

"from=no-reply%40mydomain.fr....."
```

## Cause

hackney is used within the [Mailgun Adapter](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/adapters/mailgun_adapter.ex#L86) and seems to duplicate the content-type header as described in this issue https://github.com/benoitc/hackney/issues/388. Mailgun won't understand the body and throw the error `'from' parameter is missing` 

## Temporary Solution

Lock hackney to 1.6.5, this issue was introduced with the 1.6.6 release

**Comment by Grafikart** [comment]
Hackney new release solved this issue

**Comment by paulcsmith** [comment]
Great news. Thanks for the update @Grafikart!

**Comment by benrom** [comment]
The new Hackney release was published as 1.7, Bamboo still fetches this dependency version 1.6.6 which shows as `RETIRED`. Is it possible to change deps.get to `~>1.7` instead ?

**Comment by paulcsmith** [comment]
Hi @benrom, I'm working on releasing 1.0 release candidate. There's a bunch of stuff in master not *quite* ready for a hex release. For now I would suggest using the master branch until the RC is out. I hope that helps a bit. Sorry for the delay!

**Comment by benrom** [comment]
Hi @paulcsmith , ok I'm using master for now. Looking forward to this new release!
