### ISSUE TITLE
Issue with hackney 1.6.6

### ISSUE THREAD

**Issue by Moxide** [thoughtbot/bamboo#259]
Hello,
See [this HTTPoison issue.](https://github.com/edgurgel/httpoison/issues/226)
After an update, `Bamboo` stopped working. This was caused by `hackney` being updated to version 1.6.6, which has a bug.
The solution is to update `hackney` to 1.7.0. `HTTPoison` did this in its 0.11.1 release.

In my project, I overrode `hackney` version, but it would be great if Bamboo could update HTTPoison to 0.11.1 ;-)

**Comment by jbernardo95** [comment]
@Moxide you mean `hackney` ?

**Comment by Moxide** [comment]
Ooops sorry,  I meant hackney to 1.7.0 ;-)

**Comment by paulcsmith** [comment]
Thanks for reporting. The fix is on master :)
