### ISSUE TITLE
Allow app name in from

### ISSUE THREAD

**Issue by mlaythe** [thoughtbot/bamboo#264]
````
    new_email()
    |> to(email)
    |> from("Foo <foo@bar.io")
    |> subject("Welcome")
    |> put_text_layout({LayoutView, "email.text"})
    |> render("some_email.text")

````

How would I set my app name in the from function like shown above? I looked into Bamboo.Formatter, but would love a better explanation. Thanks!

**Comment by paulcsmith** [comment]
@mlaythe You can do it like this: `from({"My App Name", "foo@bar.io"})`

Passing a tuple as an email address let's you set the name and email address. I hope that helps!
