### ISSUE TITLE
Create New Sparkpost Adapter

### ISSUE THREAD

**Issue by genericlady** [thoughtbot/bamboo#274]
I'm having problems with the existing SparkPostAdapter project and it uses an old version of elixir and bamboo. I'm writing my own with tests to debug the problem I'm having. I keep getting an html response of 301 moved whenever I use bamboo with sparkpost. When I use sparkposts' elixir library it all works fine. So it can't be my credentials or their service. Hopefully, the new sparkpost adapter will either solve the problem or elude to a solution.

Sorry about opening a PR without permission, I thought it was going to happen against my forked copy.

feedback and thoughts would be appreciated. If this gets solved without a new adapter I'll close the PR.

**Comment by paulcsmith** [comment]
@genericlady I commented on the PR. It's totally fine that you opened it first :)

You may want to open an issue on the SparkPost adapter Repo as they will know how to help more. I've never used Sparkpost so sadly, I'm not in a position to help with it. Feel free to comment here even after I close this

**Comment by genericlady** [comment]
@paulcsmith Thanks so much, you're so kind!

I will do exactly what you say, open issues against SparkPost adapter repo and help out there. Have a good weekend!
