### ISSUE TITLE
Getting "Unexpected error" with Sendgrid Adapter

### ISSUE THREAD

**Issue by luccasmaso** [thoughtbot/bamboo#280]
I have created and tested my sendgrid api_key via curl and it works with directly with api v3. With the lib I've tried some other examples but I don't know what else I can do/test because the error is too generic. 

Thanks

```
elixir_version=1.4.2
```

My `prod.exs` config:
```
config :my_app, MyApp.Mailer,
  adapter: Bamboo.SendgridAdapter,
  api_key: System.get_env("SENDGRID_API_KEY")
```

Code:
```
defmodule MyApp.Mailer do
  use Bamboo.Mailer, otp_app: :my_app
end

...

import Bamboo.Email

mail =
    new_email() 
    |> from("no-reply@my.app") 
    |> to("some@email.com") 
    |> subject("Title") 
    |> text_body("text")

mail |> MyApp.Mailer.deliver_now
```

```
%Bamboo.Email{assigns: %{}, bcc: [], cc: [], from: {nil, "no-reply@my.app"}, headers: %{}, html_body: nil, private: %{}, subject: "Title", text_body: "text", to: [nil: "some@email.com"]}

** (Bamboo.SendgridAdapter.ApiError) There was a problem sending the email through the SendGrid API.

Here is the response:

"{\"errors\":[\"Unexpected error\"],\"message\":\"error\"}"

Here are the params we sent:

%{"from" => "no-reply@my.app", "fromname" => "", "key" => "[FILTERED]", "subject" => "Title", "text" => "Sample text", "to" => ["some@email.com"]}
```

**Comment by luccasmaso** [comment]
?

**Comment by paulcsmith** [comment]
I would contact SendGrid support or post on the Elixir forums. That error SendGrid is returning seems very cryptic so I'm not sure what the problem is. It could be that it doesn't like the fake email, but I'm not sure

**Comment by sebbean** [comment]
having same error

**Comment by coryt** [comment]
I also get this error. I've narrowed it down to something in the substitutions but I'm not sure what is the cause.

> Here is the response:
> 
> "{\"errors\":[{\"message\":\"Bad Request\",\"field\":null,\"help\":null}]}"
> 
> Here are the params we sent:
> 
> %{"content" => [%{"type" => "text/plain", "value" => "campaign.content_info.content.text"}, %{"type" => "text/html", "value" => "campaign.content_info.content.html"}], "custom_args" => %{"some_id" => "baf1a278-0cf5-4b9e-ba15-523f0d11e797"}, "from" => %{"email" => "xxxx@xxxx.com"}, "key" => "[FILTERED]", "personalizations" => [%{"substitutions" => %{"*|mergetag1|*" => ["Some Value"]}, "to" => [%{"email" => "xxxx@xxxx.com"}]}], "subject" => "Take 2 Minutes", "template_id" => "d83a8414-679c-4be9-95ba-e4a4839fd686"}

**Comment by sunloverz** [comment]
Hi guys! I'm getting the same error, have you managed to fix this issue?
