### ISSUE TITLE
Dynamic SMTP configuration

### ISSUE THREAD

**Issue by lonelyDog** [thoughtbot/bamboo#282]
Hi!

Is it possible to specify SMTP configuration when I send mail. My issue is admin can change these parameters (like user name/password, SMTP port and so on) on the fly. Will be nice if i can provide configuration in deliver_now/deliver_later call (as second parameter). Or may be you can point me to different way to solve it?

Thanks

**Comment by coryodaniel** [comment]
@lonelyDog not sure if the functionality exists when you opened the ticket, but I opened a similar one. It exists, its just a little hidden. See my comment on #309

**Comment by lancejjohnson** [comment]
I'm going to close this issue per the recommendation in #309. Please reopen if this is still an issue and that recommendation doesn't address the concern.
