### ISSUE TITLE
Runtime configuration

### ISSUE THREAD

**Issue by CrowdHailer** [thoughtbot/bamboo#289]
It would be helpful if bamboo could support the phoenix/distillery convention around reading configuration at runtime in releases.

i.e. in this example the API key is read from environment variables at runtime.

```elixir
config :my_app, MyApp.Mailer,
  adapter: Bamboo.MandrillAdapter,
  api_key: {:system, "MY_API_KEY"}
```

For more on this convention I'll just refer back to distillery
https://github.com/bitwalker/distillery/blob/master/docs/Runtime%20Configuration.md

**Comment by paulcsmith** [comment]
I think this is a great idea since I'm sure others would like this. This is not something we need since we use Heroku, but if someone wants to take a crack at it, I'll merge it in.

**Comment by CrowdHailer** [comment]
I have looked a bit further and it appears that the smtp_adapter already supports this for settings it uses. Which it turns out was what I really needed.

Still probably a good idea here too but not something I can address this month

**Comment by paulcsmith** [comment]
Awesome! I'm glad that will work for you :)

**Comment by k-cross** [comment]
I think you should close this, distillery docs don't recommend this method anymore. If anything, you should just write `"${MY_API_KEY}"` and use `REPLACE_OS_VARS=true` if you're building and deploying on different machines.

**Comment by paulcsmith** [comment]
Thanks for the info @k-cross!
