### ISSUE TITLE
Design decision for SparkPost adapter

### ISSUE THREAD

**Issue by richleland** [thoughtbot/bamboo#290]
Hi Thoughtbot team - I work on SparkPost's engineering team. I see that some adapters are built-in and others are external adapters. I'm trying to determine what approach you all want to see for adapters - built-in or external or blended like you have now.

I see there is a SparkPost adapter linked to that @andrewtimberlake built, which is awesome. I'd like to make some changes but based on the way you'd like to see the library go I could do either of the following:

* Make a PR on this library
* Make a PR on @andrewtimberlake's lib

I'm happy to do either. @andrewtimberlake would also like your input - not sure how actively you are using/maintaining the lib. I'm personally partial to the approach of pluggable adapters that are external to bamboo itself.

**Comment by paulcsmith** [comment]
Hi @richleland,

Thanks for reaching out. I'd like to keep adapters external to Bamboo. I just haven't had time to extract them to their own libraries. We are actively using Bamboo and I just released 1.0rc about a week ago.

I think the best way forward would be to work on @andrewtimberlake's SparkPost adapter or fork your own version. I'm happy to link to external adapters as I've done with Andrew's and others. At some point after the launch of 1.0 I'll move all adapters out of Bamboo core into their own repo's.

Thanks for reaching out and LMK if that answers our question or if you need more info

**Comment by richleland** [comment]
Perfect thanks for the quick response @paulcsmith.
