### ISSUE TITLE
Attach custom data variables with Mailgun adapter

### ISSUE THREAD

**Issue by jfcalvo** [thoughtbot/bamboo#305]
I don't see any clear way to set custom data variables to emails using the Mailgun adapter as defined on [Mailgun documentation](https://documentation.mailgun.com/en/latest/user_manual.html#attaching-data-to-messages)

The way to add these custom variables is defined in the documentation as follows:

```
API: Pass the following parameter, “v:my-custom-data” => “{“my_message_id”: 123}”.
```

It would be nice to have some way to pass additional parameters to the API request made by the adapter but I don't see any.

**Comment by jfcalvo** [comment]
@princemaple any ideas with this one?

**Comment by princemaple** [comment]
Hi @jfcalvo I'm not a maintainer of bamboo.
You can send a PR to bamboo to add this particular functionality, which isn't very hard to implement.
Alternatively, you can use [Swoosh](https://github.com/swoosh/swoosh), which has this functionality implemented. https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/mailgun.ex#L77 You can use it by adding `%{custom_vars: ...}` to `provider_options` https://github.com/swoosh/swoosh/blob/master/lib/swoosh/email.ex#L437-L440

**Comment by princemaple** [comment]
Swoosh also supports sending attachments in all adapters, including SMTP.

**Comment by jfcalvo** [comment]
I have everything integrated with Bamboo at the moment so moving to Swoosh is not an option.

I have created a PR with the feature: https://github.com/thoughtbot/bamboo/pull/306

Thanks for your help @princemaple

**Comment by jfcalvo** [comment]
PR #306 merged so closing the issue. 

Thank you all.
