### ISSUE TITLE
"Remove" and "Remove all" buttons in Bamboo.EmailPreviewPlug

### ISSUE THREAD

**Issue by kwando** [thoughtbot/bamboo#311]

**Comment by lancejjohnson** [comment]
@kwando As this issue has been open for a while, I'm going to close it for now. If this is still something you're interested in, will you please provide more information on what you're requesting?

**Comment by kwando** [comment]
I think I wanted buttons for removing sent mails in the UI. 
This is not important for me anymore, I’ve moved away from the ruby ecosystem.
Thx for your time!
