### ISSUE TITLE
Sending in batches

### ISSUE THREAD

**Issue by mlaythe** [thoughtbot/bamboo#313]
I'm trying to send over 100k emails efficiently, and I was wondering when I pass an array of emails to the `to` method, if it's actually sending it in batches or one-by-one. Thanks for all the help =)

ex. `new_email |> to(array_of_emails)`

**Comment by paulcsmith** [comment]
This partly depends on the adapter. On Mandrill for example, Bamboo will send just one API call, and Mandrill will send one email per person in the `to` field. I think most other APIs and adapters do this as well, but you'd need to check the API docs of your service to see how it handles the `to` field to be sure.

I hope that helps :)
