### ISSUE TITLE
Render layout without view

### ISSUE THREAD

**Issue by bjunc** [thoughtbot/bamboo#317]
First, I'm new to Elixir and Phoenix, so apologies in advance for any seemingly obvious answers.

I am attempting to create a layout that can be used as a wrapper, but _without_ a view.  The Bamboo examples seem to imply this is possible, but my layout does not render when using `put_html_layout`.  The email simply sends `html_body` and `text_body` without the layout wrapper.  Instead, I need to use `render("foo.html")`, but then I am not sure how to receive the `html_body` to inject into the view.  Do I now need to use `assigns` instead?

Thanks.

**Comment by lancejjohnson** [comment]
@bjunc If you've been unable to find a solution to your question above, would you mind positing it on StackOverflow (https://stackoverflow.com/questions/tagged/elixir+bamboo)? It will get attention from more people than in this issue tracker. Thanks!
