### ISSUE TITLE
Should assign/3 be part of Bamboo.Email rather than Bamboo.Phoenix?

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/bamboo#322]
Curious why `assign/3` is part of `Bamboo.Phoenix` and not `Bamboo.Email`. `Bamboo.Email` provides `assigns` as part of its struct so it seems like manipulating that value should be the responsibility of `Bamboo.Email`.

**Comment by germsvel** [comment]
Hi @anthonator, thanks for this issue! I realize it's been quite some time, so thanks for the patience on both of the issues you opened. This is a good question. I wonder if this will get automatically resolved if we introduce a view layer/eex rendering pipeline via https://github.com/thoughtbot/bamboo/issues/541. I image we'll either have a new `assign/3` function for the new eex rendering layer or the current one would move to a more central location.

**Comment by germsvel** [comment]
The `assign/3` function is now part of [Bamboo.Template](https://hexdocs.pm/bamboo/Bamboo.Template.html#assign/3), which was introduced in https://github.com/thoughtbot/bamboo/pull/576. I'm gonna go ahead and close this issue, but let me know if you think it should be reopened. Happy to do so.
