### ISSUE TITLE
Better view support

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/bamboo#323]
I'm curious if Bamboo has any plans on adding better view support. Currently, if you want to use views at all you need to piggyback off of Phoenix. This makes those of us not using Phoenix sad 🙁

Is there any interest in adding a generic view implementation to Bamboo?

**Comment by germsvel** [comment]
Hi @anthonator, I realize this issue has been open for quite some time. Thanks for the patience! I'm starting to maintain Bamboo, and I just wanted to let you know that this work might happen. If you're interested, there's a discussion in https://github.com/thoughtbot/bamboo/issues/323 (I saw that issue before I saw this one).

**Comment by germsvel** [comment]
Hi @anthonator, if this is something you're still interested in, I just opened a PR to introduce a view/template layer into Bamboo. I'd love to hear your thoughts. https://github.com/thoughtbot/bamboo/pull/576

**Comment by germsvel** [comment]
Closing this because https://github.com/thoughtbot/bamboo/pull/576 is merged.
