### ISSUE TITLE
Deprecate SendgridHelper links

### ISSUE THREAD

**Issue by dbernheisel** [thoughtbot/bamboo#324]
When 1.0 is published, remove `SendgridHelper` Readme link:
`[Bamboo.SendGridHelper](https://hexdocs.pm/bamboo/Bamboo.SendgridHelper.html)`

Keep the `SendGridHelper` link

**Comment by JamieREvans** [comment]
This is the last item remaining in the 1.0 milestone. Is 1.0 ready to go? If so, I can open a PR to update this to get 1.0 rolling.

There are a number of important fixes in 1.0 and it's been a year since an official release, so let me know if there's anything else pending, I'd be happy to help.

**Comment by JamieREvans** [comment]
@paulcsmith Any updates?

**Comment by paulcsmith** [comment]
Bamboo 1.0 is out and the links should all work now!
