### ISSUE TITLE
Allow sending custom args through SendGrid adapter

### ISSUE THREAD

**Issue by coryt** [thoughtbot/bamboo#331]
It looks like there is no way to send custom args through to SendGrid.

I would like to add support for this and it looks like it could be done by using the `private` map and exposing a function within the SendGridHelper to add custom args...

Thoughts?

**Comment by lancejjohnson** [comment]
@coryt If this is still an interest, please open a pull request with your recommended changes. Thanks!

**Comment by germsvel** [comment]
Closing this issue (like we closed the associated PR https://github.com/thoughtbot/bamboo/pull/332) because it seems like https://github.com/thoughtbot/bamboo/pull/413 might be sufficient for sending custom args. If this should be reopened, please let me know. I'd be happy to do so.
