### ISSUE TITLE
SendGrid error sending substitutions

### ISSUE THREAD

**Issue by coryt** [thoughtbot/bamboo#333]
This is currently broken in master and was working before PR https://github.com/thoughtbot/bamboo/pull/293.

The issue seems to be that the payload being sent to SendGrid is using array of substitution values:
`"substitutions":{"test":["value"]}`
but the payload should be:
`"substitutions":{"text":"value"}`

This results in a cryptic response from the SendGrid api:
`"{\"errors\":[{\"message\":\"Bad Request\",\"field\":null,\"help\":null}]}"`

I have this fixed and working locally. I'll open a PR shortly.

**Comment by manukall** [comment]
I'm running into the same problem. do you plan to merge the associated PR?

**Comment by Strayer** [comment]
As I already commented in the PR, I think this is fixed with https://github.com/thoughtbot/bamboo/pull/337
