### ISSUE TITLE
Allow sending categories through SendGrid adapter

### ISSUE THREAD

**Issue by coryt** [thoughtbot/bamboo#335]
Similar to https://github.com/thoughtbot/bamboo/issues/331, it looks like there is no way to send categories through to SendGrid. Allowing categories to be sent is needed to collect stats via the `category stats` api.

I will take the same approach to implement this feature as in my above open issue unless there is a better way to add this.

**Comment by apbendi** [comment]
Hey @coryt, we could use this too and I'm thinking of taking a stab at implementing it. Did you have any luck getting this working on your project? Cheers!

**Comment by coryt** [comment]
@apbendi yeah the PR I have open is working and I'm using it on my project without issue.

**Comment by apbendi** [comment]
@coryt Thanks for the response and for your work on the PR! Much appreciated.

**Comment by jhsbeat** [comment]
I hope the PR for this issue could be merged upstream and in use. :)

**Comment by apbendi** [comment]
Hey @jhsbeat, you may want to reiterate your request on #339, which is the pull request where @coryt implemented this feature :)

**Comment by maymillerricci** [comment]
Closing this since #339 was merged.
