### ISSUE TITLE
Mailgun tagging (duplicate headers issue)

### ISSUE THREAD

**Issue by alexparker** [thoughtbot/bamboo#343]
### Expected:
```
email
|> put_header("X-Mailgun-Tag", "TAG1")
|> put_header("X-Mailgun-Tag", "TAG2")

Headers:

X-Mailgun-Tag: TAG1
X-Mailgun-Tag: TAG2
```

### Current result:
```
Headers:

X-Mailgun-Tag: TAG2
```

Since the `headers` property of the %Bamboo.Email struct is a map, only the last of a header key gets written to the headers of the email.

**Comment by lancejjohnson** [comment]
@alexparker Thanks for the request. As this issue is variant on a theme, I've opened #469 to combine them into a single issue and am closing this issue to track it in one place.
