### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by njwest** [thoughtbot/bamboo#347]
Under Viewing Sent Emails in the ReadMe, the `See Bamboo.SentEmailViewerPlug` link is broken, redirects to the following 404-serving URL: https://hexdocs.pm/bamboo/Bamboo.SentEmailViewerPlug.html

**Comment by dnsbty** [comment]
That link will work once the docs are updated for 1.0. The readme for 0.8 has the correct current link:
https://github.com/thoughtbot/bamboo/tree/d0b23c017e7b14ba1e130d6bd188406d86aa66f8

**Comment by paulcsmith** [comment]
@njwest Thanks for submitting. I'm going to push out a new release of 1.0 soon. Sorry for the hassle with the broken link
