### ISSUE TITLE
deliver/2 shouldn't raise exception

### ISSUE THREAD

**Issue by chingan-tsc** [thoughtbot/bamboo#355]
Hi I am currently using a Postmark adapter for Bamboo and I am noticing that `deliver_now/1` will raise an exception if something goes wrong, now AFAIC it might be confusing as functions that raise exception should be appended with a bang !. 

I am proposing maybe we should have both `deliver_now!` and `deliver_now` in the spec that all the adapters can then respect the spec later on. What do you think?

Related issue: https://github.com/pablo-co/bamboo_postmark/issues/20

**Comment by poops** [comment]
I came here to start the same discussion. Currently I have a script that bulk sends, and a timeout is throwing an exception and blocking the rest from sending. Wasn't expecting `deliver_now/1` to raise.

**Comment by awochna** [comment]
I agree. Additionally, it's probably worth noting the Bamboo.TestAdapter doesn't have a clear way to help you test how your application will handle an exception being raised during delivery.

**Comment by codyjroberts** [comment]
Agreed. The option to have standard `{:ok, _}/{:error, _}` return values would be handy.
