### ISSUE TITLE
Can't use with PowerAssert

### ISSUE THREAD

**Issue by fuelen** [thoughtbot/bamboo#358]
in test file
```
  use PowerAssert
  use Bamboo.Test

  test "user registration" do
    # ...
    assert_delivered_email ProjectWeb.Emails.welcome_email(user)
  end
```
and I got the following error

```
** (CompileError) test/project/accounts/accounts_test.exs:13: function assert/1 imported from both ExUnit.Assertions and PowerAssert.Assertion, call is ambiguous
```

I'd like to use PowerAssert in my tests, but I can't because of Bamboo.Test implementation

**Comment by lancejjohnson** [comment]
@fuelen Can you please send a pull request with your proposed changes? Thanks!

**Comment by germsvel** [comment]
I'm going to close this since we haven't heard from this. I'm not sure if it's still an issue. If it is, please let me know. I'd be happy to reopen this!
