### ISSUE TITLE
Support for multiple "received" headers?

### ISSUE THREAD

**Issue by drernie** [thoughtbot/bamboo#360]
`put_header` seems to generate a simple Map:
```
     headers: %{
             "Content-Type" => "multipart/mixed",
             "Date" => "Fri, 26 Apr 2013 11:50:29 -0700",
             "In-Reply-To" => "<517AC78B.5060404@mg.igwet.com>",
             "Message-Id" => "<517ACC75.5010709@mg.igwet.com>",
             "Mime-Version" => "1.0",
             "Received" => "from [10.20.76.69] (Unknown [50.56.129.169]) by mxa.mailgun.org with ESMTP id 517acc75.4b341f0-worker2; Fri, 26 Apr 2013 18:50:29 -0000 (UTC)",
             "References" => "<517AC78B.5060404@mg.igwet.com>",
             "Subject" => "Re: Sample POST request",
             "User-Agent" => "Mozilla/5.0 (X11; Linux x86_64; rv:17.0) Gecko/20130308 Thunderbird/17.0.4",
             "from" => "Bob <bob@mg.igwet.com>",
             "recieved" => "me 2",
             "sender" => "bob@mg.igwet.com",
             "to" => "Alice <alice@mg.igwet.com>"
           }
```
Thus, the only way to generate multiple `Received` headers is to vary the case, which is a bit odd.  RFC itself explicitly supports multiple Received headers:
https://tools.ietf.org/html/rfc822#section-4.3

>      4.3.2.  RECEIVED
     
        A copy of this field is added by each transport  service  that
        relays the message.  The information in the field can be quite
        useful for tracing transport problems

Or, is "forwarding emails" explicitly outside the use case of Bamboo?

For my purposes, it would be great if `put_header` was smart enough to generate a list of received headers and expend them to individual lines when generating the actual email.

**Comment by lancejjohnson** [comment]
@drernie Thanks for the request. As this issue is variant on a theme, I've opened #469 to combine them into a single issue and am closing this issue to track it in one place.
