### ISSUE TITLE
Broken Links in Github Readme

### ISSUE THREAD

**Issue by njwest** [thoughtbot/bamboo#361]
There are multiple broken links to Bamboo hexdocs in the Github Readme:

1. Sendgrid Helper doc link in Readme.md: **https://hexdocs.pm/bamboo/Bamboo.SendGridHelper.html**
- Should be: **https://hexdocs.pm/bamboo/Bamboo.SendgridHelper.html**

2. Send Emial Helper doc link in Readme.md: **https://hexdocs.pm/bamboo/Bamboo.SentEmailViewerPlug.html**
- Should be: **https://hexdocs.pm/bamboo/Bamboo.SentEmail.html**

**Comment by paulcsmith** [comment]
These should all be fixed now that Bamboo 1.0 is published
