### ISSUE TITLE
Creating in-memory mail attachments

### ISSUE THREAD

**Issue by npac** [thoughtbot/bamboo#364]
Recently I wrote a background service which monitors a database and sends emails about the status. Each email has an attached CSV file. I am not able to find an example on how to create such attachments without first creating files in the file system. There are examples on how to attach existing files to an email, but none showed how to create attachments in-memory. 
I was able to achieve my goal by creating `Attachment` struct and setting `data` field with content i want to send.  
```elixir 
   csv_attachment = %Attachment{
      path: nil,
      data: data,
      filename: filename,
      content_type: "text/csv"
    }

    email
    |> put_attachment(csv_attachment)
```
Do you think `Attachment` module API can be extended to support in-memory function? 
I can submit a PR for this enhancement.  
Thanks.

**Comment by Sgoettschkes** [comment]
A way to do this is outlined in https://github.com/thoughtbot/bamboo/issues/400#issuecomment-409294935

**Comment by germsvel** [comment]
Hi @npac thanks for opening this issue, and thanks for the patience! I'm beginning to maintain Bamboo, so I'm going through all the issues. 

it seems to me like this is something that is already possible in the way you described it: by passing a Bamboo attachment with `data` to the `put_attachment/2` function. 

Did you have something else in mind when you say an in-memory mail attachment? 

Also, I know it's been a while, so if this is no longer something you're interested in, we can close the issue too. Thanks again!

**Comment by germsvel** [comment]
I'll close this since it doesn't seem like it might be a need anymore. If others run into this, I'd be happy to reopen the issue or feel free to create a new one.
