### ISSUE TITLE
Validating emails prior to send email

### ISSUE THREAD

**Issue by speeddragon** [thoughtbot/bamboo#380]
Hi, I'm using bamboo and it is working great. I've notice that I didn't validate the email address before sending an email (or on register the email on the database).

Shouldn't bamboo provide some method to validate emails ? And also shouldn't that be used to validate the email before send ?

**Comment by denvaar** [comment]
I think I have the same question as you: https://github.com/thoughtbot/bamboo/issues/403

**Comment by lancejjohnson** [comment]
@speeddragon Thanks for the question and recommendation for improvement. Can you describe in more detail what you mean by validating email addresses? Do you mean comparing the provided email address with some regular expression? Or do you mean validating the email address against a remote service?

**Comment by speeddragon** [comment]
Looking back, I didn't add enough information to this issue, so know I don't remember exactly what was the problem. I think it was the email field wasn't checked against a regex for email validation. Either way, looking at #403 looks to be a good improvement and might solve this issue.
