### ISSUE TITLE
Hex Docs outdated for Bamboo.EmailPreviewPlug

### ISSUE THREAD

**Issue by mnussbaumer** [thoughtbot/bamboo#395]
Hi, I just noticed that the docs in hex refer to `Bamboo.EmailPreviewPlug` which doesn't work as it's `Bamboo.SentEmailViewerPlug` if I'm correct?

I can file a PR but I haven't found the docs anywhere to do it?

**Comment by maymillerricci** [comment]
@mnussbaumer Thanks for reporting! I wonder if you are looking at the docs for an outdated version? The current docs are [here](https://hexdocs.pm/bamboo/Bamboo.SentEmailViewerPlug.html).

**Comment by mnussbaumer** [comment]
@maymillerricci Looks fine! I honestly don't remember where I was looking at that time it's been a while
👍

**Comment by maymillerricci** [comment]
Okay great! And sorry for the delay. 😄 I'm going to close this.
