### ISSUE TITLE
attach files to email without saving content to local file

### ISSUE THREAD

**Issue by charedim** [thoughtbot/bamboo#400]
I have some binary content and would like to attach to email

the simple way is:
```
  content = <<binary-content>>
  File.write("/tmp/myfile.pdf", content )
  data = new_email()
      |> to(email)
      |> from( "email.com")
      |> subject("subject")
      |> put_attachment("/tmp/myfile.pdf")
      |> put_header("Reply-To", "email.com")
      |> html_body(html_body)
  File.rm("/tmp/myfile.pdf", content )
```

is there a way attach files without saving them locally?
something like:
```
  content = <<binary-content>>
  data = new_email()
      |> to(email)
      |> from( "email.com")
      |> subject("subject")
      |> put_attachment(content)
      |> put_header("Reply-To", "email.com")
      |> html_body(html_body)
```

**Comment by joeyrosztoczy** [comment]
I found the ability to do this via digging in the source, would people be cool with it if I updated the source docs to show the %Bamboo.Attachment{} struct ability to do this, and add a blurb on it to the started README?

**Comment by paulcsmith** [comment]
That'd be wonderful!

**Comment by marpo60** [comment]
This should work:

```
  content = <<binary-content>>
  data = new_email()
      |> to(email)
      |> from( "email.com")
      |> subject("subject")
      |> put_attachment(%Bamboo.Attachment{filename: "filename", data: content})
      |> put_header("Reply-To", "email.com")
      |> html_body(html_body)
```

**Comment by lancejjohnson** [comment]
@joeyrosztoczy Are you still interested in providing some documentation around this suggestion? If for, can you open a pull request with your recommended changes?

**Comment by germsvel** [comment]
This seems to be documented on https://hexdocs.pm/bamboo/Bamboo.Email.html#put_attachment/2. I'm not sure if that got added before or after this issue. But I'm going to close this since it seems resolved. 

If I misunderstood and we should reopen this, please let me know! I'd be happy to do it.
