### ISSUE TITLE
Return values and exceptions for `Bamboo.Mailer.html.deliver_now/1`

### ISSUE THREAD

**Issue by nathanl** [thoughtbot/bamboo#409]
I'm using Bamboo with https://github.com/fewlinesco/bamboo_smtp.

[The docs for `Bamboo.Mailer.deliver_now/1`](https://hexdocs.pm/bamboo/Bamboo.Mailer.html#deliver_now/1) don't say what return value to expect in case of success or what return value or exception I should expect in case of failure.

My experiments say that on success, I'll get back a bare `%Bamboo.Email{}` (not wrapped in `{:ok, val}`. If I use a bogus SMTP server name or credentials, a `%Bamboo.SMTPAdapter.SMTPError{}` is raised.

Sending to a bogus recipient returns a `%Bamboo.Email{}` as if it were successful, presumably because the SMTP server responded successfully and only later realized it couldn't deliver the email.

I'm not sure whether or how you'd want this documented, but I figured that someone might at least stumble on this issue and be helped a bit.

**Comment by stefmona** [comment]
Would like to see something like that for Mandrill. 👍

**Comment by germsvel** [comment]
I'm gonna go ahead and close this since Bamboo can now return ok/error tuples since https://github.com/thoughtbot/bamboo/pull/571. Let me know if you think this should still be open. Happy to reopen it if that's the case.
