### ISSUE TITLE
Sendgrid new vs legacy templates

### ISSUE THREAD

**Issue by ukutaht** [thoughtbot/bamboo#429]
Hi,

I'm trying to use Bamboo with Sendgrid templates. When I select the template ID from sendgrid:
<img width="475" alt="screen shot 2018-08-31 at 11 33 50" src="https://user-images.githubusercontent.com/3731516/44902110-c79ffb80-ad11-11e8-9f17-803b308cc577.png">

And try to use that template with Bamboo:

<img width="567" alt="screen shot 2018-08-31 at 11 34 37" src="https://user-images.githubusercontent.com/3731516/44902153-dedee900-ad11-11e8-996d-21bc600d2c5f.png">

I get the following error:

```
 ** (RuntimeError) expected the template_id parameter to be a UUID 36 characters long, got d-6589648f0fcb4d1ba45dd7a82530e50e
        (bamboo) lib/bamboo/adapters/send_grid_helper.ex:35: Bamboo.SendGridHelper.with_template/2
```
It works with legacy Sendgrid templates which do have a 36 character UUIDs. Ideally I'd like to use the new handlebars templates supported by sendgrid.

**Comment by ukutaht** [comment]
Apologies. Pull request #426 addresses this issue.

Looking forward to getting it merged.

**Comment by mackshkatz** [comment]
@ukutaht I ran across the same issue as you, and thanks to your link found the fork that solves the issue, but I'm running into another problem. I'm unsure of what the rest of the pipeline needs to look like. It seems like if I don't call `render`, the email doesn't generate properly. But if I specify `render` along with `with_template`, it doesn't use the transactional template from sendgrid and instead the template passed into render, I'd love it if I could see your full pipeline! Thanks in advance!

**Comment by ukutaht** [comment]
@mackshkatz  this is all I do:
```
    new_email()
    |> from({"<REDACTED>", "<REDACTED>"})
    |> to(user_email)
    |> with_template("d-ceefbc8d8e704256a519601beacc386b")
    |> add_dynamic_field(:name, host_name)
    |> with_categories(["host-welcome-email"])
```

And send that off as is. I never call render on it. And I'm using this fork:
`{:bamboo, git: "https://github.com/Aleksion/bamboo.git"}`

**Comment by mackshkatz** [comment]
@ukutaht thanks so much! I have a final question about your testing flow in your dev environment. Did you have to create an api key specifically for dev to actually use the templates? And then by testing, were your emails actually going out?

**Comment by ukutaht** [comment]
@mackshkatz I don't really have the flow figured out. I did not create a specific key.

It's not the best solution but I don't really test the templates and content locally. The most I test locally is to see the `%Bamboo.Email{}` sent in the logs. I do some more real testing on staging with the real sendgrid API key.

I do want to come up with a flow that makes sense for local -> stage -> prod. Luckily I'm in a position where I can test things in prod and a bit of breakage is not a huge deal so I haven't invested in figuring this out yet.

**Comment by mackshkatz** [comment]
@ukutaht Thanks for the response! Much appreciated.

**Comment by mackshkatz** [comment]
@ukutaht In case this helps you, I came up with a solution for testing in whatever environment you are dealing with. You can create a custom strategy that essentially acts like a callback allowing you to hook into the email lifecycle, and right before delivering it, you can update the `to` field and that way you don't have to worry about actually sending emails to real users but still being able to test everything in dev or staging etc. https://hexdocs.pm/bamboo/Bamboo.DeliverLaterStrategy.html

Here is my Strategy:
```elixir
defmodule Bamboo.StagingStrategy do
  @behaviour Bamboo.DeliverLaterStrategy

  def deliver_later(adapter, email, config) do
    Task.async(fn ->
      email = %{email | to: "whoever@whatever.com"}

      adapter.deliver(email, config)
    end)
  end
end
```
