### ISSUE TITLE
Make bamboo JSON encoder independent 

### ISSUE THREAD

**Issue by pradosh987** [thoughtbot/bamboo#440]
Now that Phoenix Framework 1.4 has moved to Jason for json encoder, bamboo should make itself json encoder independent. Both Jason and poison has almost similar api and it seems redundant to have two similar library in app.

**Comment by jacruzca** [comment]
I just found this in the documentation:

> You can customize it to use another library via the :json_library configuration:
    `config :bamboo, :json_library, SomeOtherLib`

I was able to test it successfully using Jason like this:

`config :bamboo, :json_library, Jason`

**Comment by paulcsmith** [comment]
Yes this was added in #374. Thanks for mentioning the new option here @jacruzca!

**Comment by lasseebert** [comment]
I'm not sure this is out in the current version (1.1.0). At least in 1.1.0, Poison is still a required dependency.
