### ISSUE TITLE
Read Me test section needs updating

### ISSUE THREAD

**Issue by joshchernoff** [thoughtbot/bamboo#441]
When trying to learn how I should be writing tests for emails I read the readme. 

In the readme under testing 
https://github.com/thoughtbot/bamboo/blob/master/README.md#testing

it states an example like so. 
```
 test "welcome email" do
    # Unit testing is easy since the email is just a struct
    user = new_user

    email = Email.welcome_email(user)

    assert email.to == user
    # The =~ checks that the html_body contains the text on the right
    assert email.html_body =~ "Thanks for joining"
  end
```

The `assert email.to == user` is misleading and fails to highlight there is a helper to address that as seen here https://github.com/thoughtbot/bamboo/blob/e2816b8a7fec5ff19b8fa5c28cbdb840793d34dc/test/lib/bamboo/adapters/test_adapter_test.exs#L57

In addition to that the test would fail as written unless `user` was assumed to be a keyword list where the key is nil as my test as failed like so. 

```
2) test confirm_request (ElixirGroupWeb.EmailTest)
     test/elixir_group_web/email_test.exs:23
     Assertion with == failed
     code:  assert email.to() == user.email()
     left:  [nil: "email-0@example.com"]
     right: "email-0@example.com"
     stacktrace:
       test/elixir_group_web/email_test.exs:28: (test)
```

**Comment by maymillerricci** [comment]
@joshchernoff Thanks for reporting! Can you provide your code for the failing test and the email function definition? What are you passing in to the `to` in the email  function? The `assert_email_delivered_with` helper is meant to be used for integration tests in the case where an email would have been sent (like in the "after registering, the user gets a welcome email") example in the [README](https://github.com/thoughtbot/bamboo/blob/master/README.md#testing), vs. that `assert email.to == user` example is for the "welcome email" unit test case where the mail is only being built and not being sent yet. Not sure if any of that helps?

**Comment by joshchernoff** [comment]
Its been a while so I will see if I can reproduce,

**Comment by lancejjohnson** [comment]
@joshchernoff Some changes have been made to the README recently. Can you review [the testing section](https://github.com/thoughtbot/bamboo/#testing) and see if those changes address your concern?

**Comment by joshchernoff** [comment]
Sorry, its been so long. 

I've started to re-review this issue again and have public code to reproduce this issue. 

First, to rule out an issue with versions I've been able to repro this on `{:bamboo, "~> 1.4"}` as of today

to see this issue please review:
https://github.com/PDX-Elixir-Group/elixir.group/blob/master/test/elixir_group_web/email_test.exs#L25-L34

```
@tag login: @user.email
  test "confirm_request", %{conn: conn, user: user} do
    email = Email.confirm_request(conn, user.email, "foo")

    assert email.to == [nil: user.email]
    assert email.from == {"No Reply | Elixir.Group", "noreply@elixir.group"}
    assert email.subject == "Elixir.group | Confirm your account"
    assert email.html_body =~ "A new user was created for the email address of #{user.email}"
    assert email.html_body =~ Routes.confirm_path(conn, :index, key: "foo")
  end
```

If you notice the `assert email.to == [nil: user.email]`

We can first start by looking at the values passed into `Email.confirm_request(conn, user.email, "foo")` in this test. I'm gonna skip over the `conn` since there does not look to be an issue with it. 
Then if we look at the value `user.email` we can see its coming from `@user params_for(:user)` which if if we `IO.inspect(user.email)` we will get back in this case a string `"email-0@example.com"` and as for `"foo"` its a string litteral as well. 

We can then go into `ElixirGroupWeb.Email.confirm_request` to look at how therese values are being used.  https://github.com/PDX-Elixir-Group/elixir.group/blob/master/lib/elixir_group_web/email.ex#L94-L98
```
  @doc """
  An email with a confirmation link in it.
  """
  def confirm_request(conn, address, key) do
    prep_mail(address)
    |> put_html_layout({ElixirGroupWeb.Mailer.LayoutView, "email.html"})
    |> subject("Elixir.group | Confirm your account")
    |> text_body("Confirm your email here http://www.example.com/confirm?key=#{key}")
    |> assign(:address, address)
    |> assign(:key, key)
    |> assign(:conn, conn)
    |> render("invite.html")
    |> Mailer.deliver_later()
  end
```
following into `prep_mail(address)` we see
```
  defp prep_mail(address) do
    new_email()
    |> to(address)
    |> from({"No Reply | Elixir.Group", "noreply@elixir.group"})
  end
```

If we IO.inspect out the results of `prep_mail` we see
```
%Bamboo.Email{
  assigns: %{},
  attachments: [],
  bcc: nil,
  cc: nil,
  from: {"No Reply | Elixir.Group", "noreply@elixir.group"},
  headers: %{},
  html_body: nil,
  private: %{},
  subject: nil,
  text_body: nil,
  to: "email-0@example.com"
}
```
At this point the `to` values remains to be a string literal. 

Following along a little deeper on the same pipe line in `confirm_request` if I insepct after the render("invite.html") IE
```
    |> assign(:conn, conn)
    |> render("invite.html")
    |> IO.inspect()
```
I still see the string as a litteral. 
```
%Bamboo.Email{
 [...]
  to: "email-0@example.com"
}
```
But after I call `|> Mailer.deliver_later()` next in the pipline if I then inspect after that I start to see the issue.  IE
```
    ...
    |> render("invite.html")
    |> Mailer.deliver_later()
    |> IO.inspect()
````
will produce

```
%Bamboo.Email{
  [...]
  to: [nil: "email-0@example.com"]
}
```

Again this is in the context of running my test via. 
`mix test test/elixir_group_web/email_test.exs:26`

Reviewing my `ElixirGroupWeb.Mailer`
https://github.com/PDX-Elixir-Group/elixir.group/blob/master/lib/elixir_group_web/mailer.ex
```
defmodule ElixirGroupWeb.Mailer do
  use Bamboo.Mailer, otp_app: :elixir_group

  defmacro __using__(:view) do
    quote do
      use Phoenix.View,
        root: "lib/elixir_group_web/templates",
        namespace: ElixirGroupWeb.Mailer

      # Import convenience functions from controllers
      import Phoenix.Controller, only: [get_flash: 1, get_flash: 2, view_module: 1]

      # Use all HTML functionality (forms, tags, etc)
      use Phoenix.HTML

      alias ElixirGroupWeb.Router.Helpers, as: Routes
      import ElixirGroupWeb.Gettext
    end
  end
end
```
I don't see any reason why the issue would happen there. At this point I assume the issue is isolated to methods coming from `use Bamboo.Mailer` I've yet to dive into that yet. But I will update as I do.

**Comment by joshchernoff** [comment]
After digging deeper I found the function in question that formats the email address to a KW list where the key is nil. 

In short `
deliver_later > Bamboo.Mailer.deliver_later/2 > Bamboo.Mailer.deliver_later/3 > Bamboo.Mailer.validate_and_normalize/2 > Bamboo.Mailer.normalize_addresses/1 > Bamboo.Mailer.format/2 > Bamboo.Formatter.format_email_address/2 `

```
defimpl Bamboo.Formatter, for: BitString do
  def format_email_address(email_address, _opts) do
    {nil, email_address}
  end
end
```

As we can see running Enum.map on a thing that return a tuple will return a keyword list with first element being the key and the second being the value. 

IE:
```
iex(3)> Enum.map(["foo@bar.com"], fn i -> {nil, i} end)
[nil: "foo@bar.com"]
```

Thus 
the if the email_addresses are `["foo@bar.com"]` calling
```
defimpl Bamboo.Formatter, for: List do
  def format_email_address(email_addresses, opts) do
    email_addresses |> Enum.map(&Bamboo.Formatter.format_email_address(&1, opts)) 
  end
end

defimpl Bamboo.Formatter, for: BitString do
  def format_email_address(email_address, _opts) do
    {nil, email_address}
  end
end
```
would result in in `[nil: "foo@bar.com"]`

So in my case calling  `Mailer.deliver_later()` anywere before inspecting my email will result in my address being formatted in a way that would invalidate the test docs. I realize the test docs are meant to be a unit case in this case and that I could be calling Mailer.deliver_later() closer to the edges but this could be a good time to call out this issue so people understand the side offfect of calling Mailer.deliver_later() better.

**Comment by joshchernoff** [comment]
Maybe a call out to where you should be "sending" your emails could be a good thing to highlight in the readme. I see this only being an issue for people how find them selfs sending their emails as a part of their email composition which could be an anti-pattern but since I've not seen anything on this I'm not sure.

**Comment by joshchernoff** [comment]
Over I think the readme update called out by @lancejjohnson addresses the issue, but I think more should still be done to callout that calling deliver or deliver_later will produce a newly formatted email where the shape of the data will change.
