### ISSUE TITLE
Support Sendgrid Personalizations

### ISSUE THREAD

**Issue by cbrewster** [thoughtbot/bamboo#443]
I need to be able to send out newsletters to a list of users. I would like to be able to use the same template and fill in info with substitutions on a per-user basis. Other users also should not be able to see the other recipients of the email in the `to` field. (See https://sendgrid.com/docs/for-developers/sending-email/personalizations/#sending-two-different-emails-to-two-different-groups-of-recipients)

From looking at the SendGrid adapter, it looks like it hardcodes a single personalization entry. It would be nice if I could add multiple personalization entries for each user and be able to send out the newsletter with a single SendGrid API call.

I am happy to actually implement this, I just want to make sure I am starting in the right direction.

**Comment by maymillerricci** [comment]
@cbrewster Thanks for posting! This makes sense, and we would welcome a PR for it!

**Comment by dantswain** [comment]
I would also like this feature.  I am willing to do a PR if I can get some indication that it will get attention - it's a little vague if this repo is getting active maintenance or not (see #515)

**Comment by maymillerricci** [comment]
@dantswain We would welcome a PR for this. Thanks!
