### ISSUE TITLE
Allow dynamic configuration in Mailer functions without directly calling through to `Bamboo.Mailer`

### ISSUE THREAD

**Issue by lancejjohnson** [thoughtbot/bamboo#470]
See #309, #414, #282 for examples and use cases.

The current recommendation via #309 is to use the `Bamboo.Mailer` undocumented functions. As Bamboo discourages the use of direct calls to `Bamboo.Mailer`, it should provide the ability to accomplish this same task through the usable functions.

**Comment by sandeshsoni** [comment]
@lancejjohnson If we should not directly call functions of `Bamboo.Mailer`, should an another module be created that makes the call? 

I am checking if I can help and will be happy to contribute!

**Comment by lancejjohnson** [comment]
@sandeshsoni What I'm referring to above and probably should have clarified is that `deliver_now/1` and `deliver_later/1` on `Bamboo.Mailer` raise an exception. This is designed, I believe, to force you to define your own mailer (e.g. `MyApp.Mailer`) and use the macro `use Bamboo.Mailer` within it.  The recommendation above is to allow the work around (i.e. calling the undocumented 3 arity functions) behavior to be available through the functions provided by `use Bamboo.Mailer`. I hope that helps clarify.

**Comment by stratigos** [comment]
I believe this is now satisfied by #497 on the latest `master`
