### ISSUE TITLE
refute_delivered_email_with?

### ISSUE THREAD

**Issue by yuvalidan** [thoughtbot/bamboo#474]
Something like `refute_delivered_email_with` or the ability to pass options to `refute_delivered_email` would be super helpful. Currently I have a problem when testing emails where the html includes unique elements (like a timestamp or a token) because it would never match the email that's generated in the test.

I can make the affirmative tests work with `assert_email_delivered_with`, but have no way of testing that a similar email was *not* sent because currently only full matches are supported.

**Comment by maymillerricci** [comment]
This was implemented in #484.
