### ISSUE TITLE
Create a new release.

### ISSUE THREAD

**Issue by abuiles** [thoughtbot/bamboo#483]
We have been using a custom fork to get the functionality added here https://github.com/thoughtbot/bamboo/commit/214f5f3e3be51e15d7c2d4c7449fe1d48a6aa472 

Do you know when a new release will be out to include the changes linked above?  

Thanks!

**Comment by maymillerricci** [comment]
A new release is now out! [v1.3.0](https://hex.pm/packages/bamboo/1.3.0)
