### ISSUE TITLE
Bamboo.Formatter:format_email_address throws type error with Elixir 1.9.1

### ISSUE THREAD

**Issue by bradleygolden** [thoughtbot/bamboo#499]
`Bamboo.Formatter:format_email_address` is throwing a type error after we upgrade to Elixir 1.9.1. This is happening because we've implemented the protocol `format_email_address` but we're not passing in any of the required `opts`. We don't have a need to specify the `type` as specified here https://github.com/thoughtbot/bamboo/blob/89845a829e15078e01fc654980c2c7f33e0b16bc/lib/bamboo/formatter.ex#L66.

It seems from https://github.com/thoughtbot/bamboo/issues/41 that maybe the original intention for this function was to allow the `type` opt but also allow a no opts case.

Here's an example of how we've implemented it:

```elixir
@spec format_email_address(user_type, map) :: some_return_type
def format_email_address(user, _opts) do
  ...
end
```

An example type that I think would support this is:
```
 @type opts :: %{} | %{type: :from | :to | :cc | :bcc} 
```

Can you support the case where we can provide an empty map rather than a type?

**Comment by bradleygolden** [comment]
I'm happy to open up a PR if needed.

**Comment by halostatue** [comment]
This could be done by doing `@type opts :: %{optional(:type) => :from | :to | :cc | :bcc}`.

**Comment by germsvel** [comment]
Hi @bradleygolden, thanks for opening this issue, and thanks for the patience! I'm taking over maintenance of Bamboo and trying to go through all the issues. 

I think what you mention here makes a lot of sense. It does seem like the `opts` type is too restrictive at the moment, and at the very least we should allow an empty map. I do like the `@type opts :: %{optional(:type) => :from | :to | :cc | :bcc}` option. 

If you're still interested in this, I'd love to review a PR. But I do realize it's been a while. So if you're not up for it, I'll try to get this when I have some time.

**Comment by bradleygolden** [comment]
PR ready! https://github.com/thoughtbot/bamboo/pull/557

**Comment by germsvel** [comment]
Thanks for contributing!
