### ISSUE TITLE
Failed HTTPS Request - upgrade to hackney 1.15.2

### ISSUE THREAD

**Issue by rakusan2** [thoughtbot/bamboo#512]
This issue I am having is the same as edgurgel/httpoison#393
```elixir
{:error, {:option, :server_only, :honor_cipher_order}}
```

The same Fix works
And that is to upgrade hackney to 1.15.2

**Comment by germsvel** [comment]
Thanks for this info @rakusan2! I changed the title of the issue to (hopefully) make it more discoverable for others who run into this issue. Do you have a suggestion here for what to do with Bamboo or does it make sense to close this issue?

**Comment by rakusan2** [comment]
I would recommend bumping the minimum version of hackney to `1.15.2` since I and anyone else that encounters this issue will be overriding the version to such anyways.
benoitc/hackney#591
