### ISSUE TITLE
Support amp email bodies

### ISSUE THREAD

**Issue by mattmatters** [thoughtbot/bamboo#514]
Hey folks love the project! Sorry to hit you with a controversial feature request!

Since companies such as Mailgun and Sendgrid support amp emails, it would be nice to add the functionality to render amp templates.

Something along the lines of `amp_body` being added to `%Email{}` would be pretty useful for adapters to add this feature.

**Comment by germsvel** [comment]
Hey @mattmatters, thanks for opening this issues for discussion! I am not super familiar with amp emails (I know the concept but not how they work). Do you know of any resources that could helps us determine whether this is a good idea for the project?

**Comment by germsvel** [comment]
I'm going to close this since I haven't heard about any more interest in this. Please let me know if you'd like this to be reopened. I'd be happy to reopen it if someone has a good use case and can provide more info on amp emails.
