### ISSUE TITLE
Show attachments in SentEmailViewer

### ISSUE THREAD

**Issue by dnsbty** [thoughtbot/bamboo#520]
It would be great if the SentEmailViewer would also show attachments. I'm trying to debug some attachments right now, and it looks like I'll need to set up a different adapter for this.

**Comment by germsvel** [comment]
This sounds like a great idea @dnsbty! If you or someone else is up for it, I'd love to see a PR for this.

**Comment by hadfieldn** [comment]
I just submitted a PR for this: https://github.com/thoughtbot/bamboo/pull/553
