### ISSUE TITLE
Advanced API key definitions for sendgrid.

### ISSUE THREAD

**Issue by spunkedy** [thoughtbot/bamboo#522]
It would be great to be able to do something like the way stripity_stripe does configurations.

https://hexdocs.pm/stripity_stripe/readme.html#configuration

**Comment by spunkedy** [comment]
I did a first pass at the PR because I need to have this feature now. This works for me.

**Comment by spunkedy** [comment]
@andrewjensen I know these can be strange times, do you know if there is there a better way to communicate for this repo than github?

**Comment by andrewjensen** [comment]
Hi @spunkedy, I'm not a maintainer on this project. My PR #519 was stale for a while, so I looked through the commit history and mentioned a few people that seemed to commit/comment frequently, which helped to get it reviewed and merged.

**Comment by spunkedy** [comment]
Thanks! I appreciate it. I saw you get a merge in so I figured it would be
good to ask you.

**Comment by spunkedy** [comment]
@maymillerricci  @cpytel 

Would love to get feedback on my PR if it needs any improvement

**Comment by germsvel** [comment]
Hi @spunkedy, thanks for opening this issue and the associated PR! I'm starting to do bamboo maintenance. I know May left a few comments on the PR. Would you be up for resolving those, and we can get that PR merged?
