### ISSUE TITLE
Add ability to add attachments

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#53]
This is probably going to come a bit later since I have never needed to send an attachment in an email, it's always a link back to the app. I know this is useful to people though so it should be added.

**Comment by hdcos** [comment]
yes please, my business needs it, and currently mailgun works but doesn't support utf8 so cannot put it in production

**Comment by michalvalasek** [comment]
Any news on this issue guys?

**Comment by davekapp** [comment]
We would definitely like to take advantage of this as well, so another +1 from me.

**Comment by pradhyu** [comment]
This would be a great feature to add

**Comment by paulcsmith** [comment]
Closed by #156

**Comment by paulcsmith** [comment]
Coming in the 1.0rc1 that I will try to push to hex today

**Comment by davekapp** [comment]
That's awesome! Thank you so much!

**Comment by ijunaid8989** [comment]
@paulcsmith is there any inline attachment options available?
