### ISSUE TITLE
mailgun adapter not working in production

### ISSUE THREAD

**Issue by IlyasM** [thoughtbot/bamboo#540]
Hi, I get the following error when app deployed to digital ocean 

[error] Task #PID<0.559.0> started from #PID<0.560.0> terminating
** (Bamboo.ApiError) {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}
    (bamboo 1.5.0) lib/bamboo/api_error.ex:42: Bamboo.ApiError.raise_api_error/1
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.1924921/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
    Args: []

Everything works fine in development on local machine. What might be causing this?
Networking works fine when using Mailgun Api directly on droplet.

**Comment by fuelen** [comment]
perhaps you have different erlang or openssl versions.

**Comment by IlyasM** [comment]
yes, that was the issue. Locally on OTP22  everything worked fine. On OTP23 additionally had to, 
   |> put_private(:hackney_options, ssl_options: [versions: [:"tlsv1.2"]])
