### ISSUE TITLE
[Reopened] Bamboo API error - 406 Not acceptable - Sendgrid API (#542)

### ISSUE THREAD

**Issue by jatin759** [thoughtbot/bamboo#543]
I am getting the same error as mentioned in #542 
I tried upgrading the Bamboo package as mentioned in #542 but still getting the same error (some emails went through and some didn't).

I am using {:bamboo, github: "thoughtbot/bamboo"} in deps.

I tried both ways, with and without putting header : `put_header("accept", "application/json")` .

What might be causing it?

**Comment by germsvel** [comment]
Hey @jatin759, I'm going to close this in favor of reopening #542. That way the conversation is all in one place.
