### ISSUE TITLE
What would be needed to get bamboo_mailjet merged into bamboo?

### ISSUE THREAD

**Issue by marcinkoziej** [thoughtbot/bamboo#550]
Hi!
I am using bamboo with bamboo_mailjet. It seems that the latter package maintaining is not active, and I thought maybe Mailjet adapter could be merged into bamboo package (just like SendGrid, Mandrill). 
What would be needed to make this happen?
Is it desirable?
I'd be interested in contributing necessary changes

**Comment by germsvel** [comment]
HI @marcinkoziej, thanks for opening this issue! I've only recently started maintaining Bamboo, but my inclination would be to not merge more adapters into Bamboo itself, especially if we don't have experience with them (I haven't used mail jet). I think adapters are great as standalone packages that can iterate as needed. 

If the `bamboo_mailjet` package is unmaintained, have you considered reaching out to the maintainers of the package to offer help, transfer ownership, or fork a version and maintain it? I know maintaining open source can be a lot, so I understand if that's not part of what you want to do. I'm just trying to think of alternatives.

**Comment by marcinkoziej** [comment]
I have asked there but no response so far.

**Comment by marcinkoziej** [comment]
I got contact, let's see how that goes
