### ISSUE TITLE
Error in sent_email_viewer -> index.html.eex if more 1 sender was added to from

### ISSUE THREAD

**Issue by esurat20** [thoughtbot/bamboo#568]
I got an error when i was trying to add several senders to `from`
`no function clause matching in Bamboo.SentEmailViewerPlug.Helper.format_email_address/1`
```
def format_text_body(body) do
    HTML.html_escape(body || "")
end

def format_email_address({nil, address}), do: address

def format_email_address({name, address}) do
    "#{name} &lt;#{address}&gt;"
end
```

senders map: `[{"Test 1", "test1@mail.com"}, {"test2", "test2@mail.com"}]`

Need to add `format_email_address` variant which can handle list.

I`ve fixed this problem but can not push my branch to the repo.

**Comment by germsvel** [comment]
Thanks for pointing this out @esurat20. If you want to open a PR (I'd love to take a look at it), you have to fork the repo, push the branch to that repo, and then open a PR from that one to the `bamboo` repo. I don't think you can just push a new branch to the `bamboo` repo itself. Does that make sense?

**Comment by esurat20** [comment]
@germsvel  Yep sure. I will create a fork.

**Comment by esurat20** [comment]
@germsvel please check related PR.

**Comment by esurat20** [comment]
@germsvel any updates?

**Comment by germsvel** [comment]
Hi @esurat20, thanks for checking back on this. This slipped past me somehow. Just submitted a review. Thanks for contributing to Bamboo!
