### ISSUE TITLE
Dialyzer error with 2.0.0 version

### ISSUE THREAD

**Issue by dfalling** [thoughtbot/bamboo#587]
I'm getting a Dialyzer error on the 2.0.0 release due to the changes to `deliver_now` function:
```elixir
The @spec for the function does not match the success typing of the function.

Function:
IdoWeb.Mailer.deliver_later/1

Success typing:
@spec deliver_later(_) ::
  {:error,
   <<_::64, _::size(8)>>
   | %{
       :__exception__ => true,
       :__struct__ => Bamboo.EmptyFromAddressError | Bamboo.NilRecipientsError,
       :message => <<_::64, _::size(8)>>
     }}
  | {:ok,
     %{
       :bcc => {binary(), binary()},
       :cc => {binary(), binary()},
       :from => {binary(), binary()},
       :to => {binary(), binary()},
       _ => _
     }}
```

I looked through the code and it looks correct, but when I clone `bamboo` and run dialyzer in it, I do get errors for `deliver_now`, but only for the version that throws an exception when called directly.

This error in my project is on this line:
```elixir
  use Bamboo.Mailer, otp_app: :ido
```

Has anyone else hit this?  I've hunted and haven't found a way to fix it in my code, but also don't see what's wrong on Bamboo's side.

**Comment by benvp** [comment]
Noticed the same issue with Bamboo 2.0.0, but didn't investigate anything yet.

**Comment by germsvel** [comment]
Thanks for opening this issue. It seems that dialyzer is complaining about `deliver_later/1`, and I think a fix has been introduced for that in https://github.com/thoughtbot/bamboo/pull/584. I haven't cut a release yet because of time, but I'm hoping to do that soon.

**Comment by dfalling** [comment]
Great, thanks!  I'll report back once that's pushed out.

**Comment by germsvel** [comment]
Just pushed Bamboo v2.0.1 which should fix this issue.

**Comment by mmzx** [comment]
Thanks for the fix!

**Comment by germsvel** [comment]
I'll go ahead and close this issue since it's been resolved. If it persists, let me know and we can reopen it.

**Comment by dfalling** [comment]
All good on my end with `deliver_now` too.  Thanks!
