### ISSUE TITLE
CaseClauseError when using LocalAdapter with open_email_in_browser_url option

### ISSUE THREAD

**Issue by SamuelWillis** [thoughtbot/bamboo#588]
Using the `LocalAdapter` with the `open_email_in_browser_url` set results in:

```
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {"", 0}
        (bamboo 2.0.1) lib/bamboo/mailer.ex:206: Bamboo.Mailer.deliver_now/4
        (bamboo 2.0.1) lib/bamboo/mailer.ex:226: Bamboo.Mailer.deliver_now!/4
```

Looking at the [`LocalAdapter@L34`](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/adapters/local_adapter.ex#L34) it seems it returns the result of the [`System.cmd`](https://hexdocs.pm/elixir/System.html#cmd/2) which doesn't match any of the clauses in the [`Bamboo.Mailer.deliver_now@L206`](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/mailer.ex#L206).

**Comment by germsvel** [comment]
@SamuelWillis thanks for opening this issue. I think I see what you're saying. It seems like the `LocalAdapter`'s `deliver_now` function that takes the `open_email_in_browser_url` isn't returning an `:ok`/`:error` tuple, right? 

I'll try to get this as soon as I can, but I'd also welcome a pull request, if you're interested in opening one.

**Comment by germsvel** [comment]
Thanks @SamuelWillis. I think returning `{:ok, result}` where `result` is whatever `System.cmd` returns would work. That would satisfy the `Bamboo.Adapter` [callback definition](https://github.com/thoughtbot/bamboo/blob/a94b83286727d71747df8c03c022f470c0a1cd49/lib/bamboo/adapter.ex#L40).

**Comment by germsvel** [comment]
#589 resolved this, so I'm going to close this.
