### ISSUE TITLE
Add support for SendGrid's unique arguments

### ISSUE THREAD

**Issue by jason-pather** [thoughtbot/bamboo#592]
SendGrid's unique arguments allow attaching a unique identifier to each email which can be used for tracking:
https://sendgrid.com/docs/for-developers/sending-email/unique-arguments/

SendGrid's Event API emits events that also contain these identifiers, allowing emails and events to be linked:
https://sendgrid.com/docs/for-developers/tracking-events/event/

Support for unique arguments would be a great addition to the SendGridHelper, which already supports a similar feature - adding categories to emails using the `with_categories/2` function:
https://hexdocs.pm/bamboo/Bamboo.SendGridHelper.html#with_categories/2

**Comment by germsvel** [comment]
Thanks for opening this issue @jason-pather. I'd be happy to review a PR for this, if you or others feel up for it. I imagine having a function like `SendGridHelper.with_unique_args(email, args)` would be good.

**Comment by jeepers3327** [comment]
I create a PR to support this one. Please kindly review my PR. 

Thank you.
