### ISSUE TITLE
Allow overriding of recipients when using in staging environment

### ISSUE THREAD

**Issue by davidlibrera** [thoughtbot/bamboo#594]
In one of our staging environment we're working using real addresses and we should avoid sending them emails.
In ruby we usually use gems like [RecipientInterceptor](https://github.com/croaky/recipient_interceptor) that allow to override all recipients (to, cc and bcc)  with a custom list of addresses and setting the original ones in headers.

We have a PR ready that includes a new adapter `RecipientReplacerAdapter` that wraps the real adapter replacing all addresses.
```
config :my_app, MyApp.Mailer,
  adapter: Bamboo.RecipientReplacerAdapter,
  inner_adapter: Bamboo.SendGridAdapter,
  recipient_replacements: ["user-1@example.com", "user-2@example.com],
  ...
```

Could it be an interesting feature?

https://github.com/thoughtbot/bamboo/compare/master...leanpanda-com:master

**Comment by maartenvanvliet** [comment]
A feature to handle use cases such as these is already being worked on 😀

See: https://github.com/thoughtbot/bamboo/pull/591

**Comment by davidlibrera** [comment]
Sorry,  I've looked in Iusses and not in existing PRs
