### ISSUE TITLE
Click Tracking settings for SendGrid Adapter

### ISSUE THREAD

**Issue by ehsieh** [thoughtbot/bamboo#596]
SendGrid allows for click tracking to be enabled/disabled on a per email basis:

https://sendgrid.com/docs/ui/account-and-settings/tracking/#click-tracking

![image](https://user-images.githubusercontent.com/885796/113368030-7fef0f80-9312-11eb-9ace-c4da2e2b7145.png)

I imagine this could be implemented in the same fashion as the current Google Analytics settings support (https://github.com/thoughtbot/bamboo/pull/462)

I'd be happy to open PR for this!

**Comment by germsvel** [comment]
Hi @ehsieh (it's good to see you!). Thanks for opening this issue. I'd be happy to review a PR. 

Even though there isn't a defined standard, most helper functions in the [SendGridHelper](https://hexdocs.pm/bamboo/Bamboo.SendGridHelper.html) use the `with_x` format to set values when composing an email (just like the google analytics PR you included). So, I imagine we could follow that pattern, unless there's a more descriptive way to set the click tracking.
