### ISSUE TITLE
Provide server config parameters in code?

### ISSUE THREAD

**Issue by packetq** [thoughtbot/bamboo#606]
Hi,

I am working on an application that needs to fallback to multiple email servers in case of failure. This would require multiple server configurations. Is there a way to provide the config parameters from code instead of the config file?

Thanks

**Comment by germsvel** [comment]
Hi @packetq, thanks for opening this issue. Would you mind providing some more information as to what you need? 

Is this something like sending emails via Sendgrid and fallback to Mailgun? I don't think there's a way to configure multiple email providers at the moment, but if you have ideas for how we could implement that, I'd be very happy to help bounce ideas and then review a PR.

**Comment by maartenvanvliet** [comment]
There's an adapter that could help here: https://github.com/fuelen/bamboo_fallback

**Comment by packetq** [comment]
Hi,

Sorry for the delay. I'm sending mail to some private mail servers. I just need a way to provide the server and account information in code. I'm new to Elixir and I like it so far. However, this whole config.exs thing is presenting quite a challenge. It seems very limiting. Something like the below would be great. Although, I don't expect something like this. This is just an example of what I need. Is there a way to provide the server config in code? I've been looking at the source and it looks like it is pretty much hardwired to the config.exs thing. Being new to Elixir, I don't think I'm ready to hack on someone else's stuff quite yet ;-). 

`server = new_server(
 adapter: Bamboo.SMTPAdapter,
      server: "x.x.x.x",
      hostname: "mailserver.mydomain.com",
      port: 25,
      username: "user@mydomain.com", 
      password: "password", 
      tls: :if_available, 
      ssl: false, 
      retries: 1,
      no_mx_lookups: false, 
      auth: :if_available 
    )

  MyMailer.Mailer.deliver_now(server, email)
`

Thanks

**Comment by germsvel** [comment]
@packetq do you know if the adapter [Maarten linked to](https://github.com/thoughtbot/bamboo/issues/606#issuecomment-854695694) would work for your use case? I think that's what I would lean towards using at the moment: https://github.com/fuelen/bamboo_fallback

**Comment by germsvel** [comment]
@packetq I'm going to close this issue for now since the `bamboo_fallback` library seems like a good solution to your issue. If that's not the case, please let me know, and I'd be happy to reopen this.
