### ISSUE TITLE
Fix options with assert_delivered_email

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#74]
It should normalize the email addresses, and should only match against the keys that are in the options. For asserting just what you pass in, do something like this

``` elixir
defmacro assert_delivered_email(email_params) do
    # Normalize the address as well
    quote do
      import ExUnit.Assertions
      assert_received({:delivered_email, unquote(email_params)})
    end
  end
```

**Comment by jbernardo95** [comment]
@paulcsmith What do you mean by options ?

This ?
```elixir
assert_delivered_email(subject: "Something")
```

**Comment by paulcsmith** [comment]
Yes exactly :) The feature did not work quite right so I believe I removed it, or at the very least removed docs so people didn't use it

**Comment by jbernardo95** [comment]
Ok, I see.

This would be backwards compatible as well, right ? Accepting an `%Email{}` or a keyword list with parameters to compare.

**Comment by paulcsmith** [comment]
Yes that is correct. It should accept either of those two options

**Comment by jbernardo95** [comment]
@paulcsmith 👍

I will open a pr regarding this :)

**Comment by jbernardo95** [comment]
@paulcsmith I have been digging through the code.

If we use the `assert_received({:delivered_email, unquote(email_params)})` method as you suggested we will lose the custom `flunk_with_email_list` error message, or we will have make all those helper functions public for it to keep working.

Something like this:

```
  defmacro assert_delivered_email(email) do
    quote do
      import ExUnit.Assertions
      email = Bamboo.Test.normalize_for_testing(unquote(email))
      try do
        assert_received({:delivered_email, ^email})
      rescue
        error in [ExUnit.AssertionError] ->
          Bamboo.Test.flunk_with_email_list(email)
      end
    end
  end
```

What do you think of this ?

**Comment by jbernardo95** [comment]
@paulcsmith Up

**Comment by paulcsmith** [comment]
@jbernardo95 I think maybe another function should be added then. Something like `assert_delivered_with`. So you'd use it like `assert_delivered_with(subject: "Welcome to the app")`

Does that help/answer the question?

**Comment by jbernardo95** [comment]
@paulcsmith Kind of, what I was saying is that if we declare `assert_delivered_email` as a macro we will have to make `flunk_with_email_list` public.

The other option we have is to put the `import ExUnit.Assertions` in the `__using__` macro and that way we don't need the macro.

Does that clarify ?

**Comment by paulcsmith** [comment]
I think making `flunk_with_email_list` public and declaring `@doc false` to it would probably work ok :D

**Comment by jbernardo95** [comment]
Yep it does ! Didn't know about hiding methods with `@doc false` but it is perfect for this case.

**Comment by jbernardo95** [comment]
@paulcsmith Here is a draft ^, take a look and tell me what you think :)

**Comment by jbernardo95** [comment]
@paulcsmith Up.
