### ISSUE TITLE
Add Mailgun adapter

### ISSUE THREAD

**Issue by stevedomin** [thoughtbot/bamboo#85]
Add an adapter for the [Mailgun API](https://documentation.mailgun.com/)

I'm starting on this one.

**Comment by paulcsmith** [comment]
Right on. Just a heads up, I only plan to keep Mandrill, Local and Test adapters in Bamboo core for now. If you ping me when you are done with a Mailgun adapter I can make a chart/list and add it to the README. I'll add all external adapters there so people can find them :)

**Comment by mtwilliams** [comment]
What's the reasoning behind only supporting Local, Test, and Mandrill adapters in core? @paulcsmith

**Comment by paulcsmith** [comment]
@mtwilliams Great question. I'm leaving Mandrill in for now because it's what we use in production so I know that it works. It also makes it so that if I change how Bamboo works I can quickly and easily test that the MandrillAdapter also works. If I add Mailgun (or whatever other adapter) it would mean I would have more adapters to update and I couldn't test them out easily since we don't use it in production. It also means that if something changes in Mailgun and I need to update the adapter, I would need to cut a new release of bamboo, even though Bamboo itself hasn't changed. I'm ok taking on that responsibility for Mandrill because we can test it on our own apps before releasing to the public.

Once Bamboo hits 1.0 I will extract the MandrillAdapter so that Bamboo core only has Local and Test adapters. I'll add instructions to the README for adding the MandrillAdapter dep and how to use it, along with a list of other third party adapters (Mailgun, SMTP, etc.)

Does that answer your question?

**Comment by mtwilliams** [comment]
I see. My thought process was why single out Mandrill. That makes total sense.

**Comment by philipgiuliani** [comment]
Is there already for a adapter as library online? I would like to work on the SMTP adapter, but its my first library so i need some example how to structure it!

**Comment by paulcsmith** [comment]
@philipgiuliani that would be awesome if you worked in an am to adapter. You can check out the mandrill adapter in this repo: https://github.com/paulcsmith/bamboo/blob/master/lib/bamboo/adapters/mandrill_adapter.ex

Also here are some basic docs on implementing an adapter: https://github.com/paulcsmith/bamboo/blob/master/lib/bamboo/adapter_behaviour.ex

I hope that helps. Feel free to comment here or ping me in Slack if you need help. There is an open issue for adding an SMTP adapter with a link to some possible SMTP libraries that could potentially be used for sending the email

**Comment by mtwilliams** [comment]
I wrote [an adapter for SendGrid.](https://github.com/mtwilliams/bamboo-sendgrid) If you have any questions, feel free to ping me.

**Comment by paulcsmith** [comment]
Nice work @mtwilliams. I'll add that to the README :D

**Comment by ricn** [comment]
@stevedomin Any progress on the Mailgun adapter?

**Comment by ricn** [comment]
@stevedomin If you don't have the time to do it right now I'm willing to create an adapter for Mailgun next week.

**Comment by paulcsmith** [comment]
@ricn I think you can go ahead and do the Mailgun adapter if you'd like :) Ping me if/when it's done and I can add it to the README :)

**Comment by jandillmann** [comment]
:+1: for a Mailgun adapter :smile:

**Comment by ricn** [comment]
I haven't got the time to implement it yet so if anyone want to step up and do it that would be great :-)

**Comment by paulcsmith** [comment]
I have a few other priorities before this so if someone wants to tackle this that would be great. You can check out the MandrillAdapter as an example https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/adapters/mandrill_adapter.ex. If someone decides to tackle this please note it here so two people don't work on it at once :D

**Comment by paulcsmith** [comment]
I've started on this

**Comment by princemaple** [comment]
FYI all https://github.com/thoughtbot/bamboo/pull/125, in case you want to review the implementation.

**Comment by paulcsmith** [comment]
Closed by #125 thanks @princemaple!

**Comment by princemaple** [comment]
@paulcsmith if you could make a new release, I'd be able to test this package in a real app soon.

**Comment by paulcsmith** [comment]
@princemaple That would be awesome if you could test it out a bit more. I have a couple more things I want to do for the next release.

What we've been doing is using the github master branch if there are features we need right away

```elixir
{:bambo, "~> 0.4", github: "thoughtbot/bamboo"}
```

That should let you test out the adapter without waiting for hex. LMK if that works for what you need :)

**Comment by princemaple** [comment]
@paulcsmith yeah I'm aware of that. I was being lazy, not wanting to add git to my docker image :)

:+1: all good, release when you feel it's ready.

**Comment by paulcsmith** [comment]
Haha ok, yeah that makes sense. I’ll try to get it out this Friday or next :)

**Comment by princemaple** [comment]
Thanks!

**Comment by Andorbal** [comment]
I'm actually looking for a non-Mandrill adapter for my app, so I can give this a try tonight.  Is there something specific you want tested?

**Comment by paulcsmith** [comment]
@Andorbal Thank you! Really anything would be fine. If it sends email it's probably fine. @princemaple Tested it, and the unit tests seem to be pretty comprehensive.

If you do run into anything though, please open up an issue :)

**Comment by Andorbal** [comment]
Will do!

**Comment by paulcsmith** [comment]
I just released Bamboo 0.5.0 to hex. This includes the new Mailgun adapter. Here is a full list of changes: https://github.com/thoughtbot/bamboo/blob/master/CHANGELOG.md

Eventually all adapters will be moved into their own repo, but for now it's in Bamboo core
