### ISSUE TITLE
Add Bamboo.Phoenix.put_layout that accepts an atom for the template name

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#91]
And use it for both the html and text layouts so you don't need to call `put_text_layout` and `put_html_layout`

**Comment by paulcsmith** [comment]
@anellis This is a smaller one that could be useful. Right now we have functions for `put_text_layout` and `put_html_layout`. I'd also love to have `put_layout(emails, {MyApp.LayoutView, :email.html})`

This would basically call

```elixir
email
|> Bamboo.Phoenix.put_text_layout({layout, to_string(template) <> ".text")
|> Bamboo.Phoenix.put_html_layout({layout, to_string(template) <> ".html")
```

Might be a good started task if you're interested!

**Comment by anellis** [comment]
@paulcsmith Awesome! I'll take a look and let you know if I have any questions
